steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/rupaykg/rupaykg:${COMMIT_SHA}
      - --build-arg
      - VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
      - --build-arg
      - VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
      - --build-arg
      - VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
      - --build-arg
      - VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/rupaykg/rupaykg:${COMMIT_SHA}

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/rupaykg/rupaykg:${COMMIT_SHA}

substitutions:
  _REGION: asia-south1
  _VITE_FIREBASE_API_KEY: REPLACE_WITH_FIREBASE_WEB_API_KEY
  _VITE_FIREBASE_AUTH_DOMAIN: REPLACE_WITH_FIREBASE_AUTH_DOMAIN
  _VITE_FIREBASE_PROJECT_ID: REPLACE_WITH_FIREBASE_PROJECT_ID
  _VITE_FIREBASE_APP_ID: REPLACE_WITH_FIREBASE_APP_ID

options:
  logging: CLOUD_LOGGING_ONLY
