import Fastify from "fastify";
import cors from "@fastify/cors";
import fastifyStatic from "@fastify/static";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { Pool, type PoolClient, type PoolConfig } from "pg";
import { authenticate, bearerChallenge, canActForOrganization, canVerifyEvidence, type AuthContext } from "./auth.js";
import { registerValueRoutes } from "./value-routes.js";
import { registerRegistryRoutes } from "./registry-routes.js";
import { registerSyncRoutes } from "./sync-routes.js";
import { registerWorkspaceRoutes } from "./workspace-routes.js";
import { registerIntelligenceRoutes } from "./intelligence-routes.js";

const app = Fastify({ logger: true });
const allowedOrigins = process.env.RUPAYKG_ALLOWED_ORIGINS?.split(",").map(origin => origin.trim()).filter(Boolean) ?? [];
await app.register(cors, { origin: allowedOrigins.length ? allowedOrigins : false });
const webRoot = resolve(process.cwd(), "apps/web/dist");
if (existsSync(webRoot)) {
  await app.register(fastifyStatic, { root: webRoot, wildcard: false });
}
const databaseUrl = process.env.DATABASE_URL;
const poolConfig: PoolConfig = { connectionString: databaseUrl, max: 10 };
if (process.env.DATABASE_SSL === "require") {
  poolConfig.ssl = {
    rejectUnauthorized: true,
    ca: process.env.DATABASE_CA_CERT,
  };
} else if (process.env.DATABASE_SSL !== "false") poolConfig.ssl = { rejectUnauthorized: false };
const pool = databaseUrl ? new Pool(poolConfig) : null;
async function query<T extends Record<string, unknown>>(text: string, values: unknown[] = []): Promise<T[]> { if (!pool) throw new Error("DATABASE_URL is not configured"); return (await pool.query<T>(text, values)).rows; }
function bodyOf(request: { body: unknown }): Record<string, unknown> { return (request.body && typeof request.body === "object" ? request.body : {}) as Record<string, unknown>; }
function requiredString(body: Record<string, unknown>, key: string): string | null { return typeof body[key] === "string" && body[key].trim() ? body[key].trim() : null; }
function requiredPositiveNumber(body: Record<string, unknown>, key: string): number | null { const value = Number(body[key]); return Number.isFinite(value) && value > 0 ? value : null; }
async function withTransaction<T>(fn: (client: PoolClient) => Promise<T>): Promise<T> { if (!pool) throw new Error("DATABASE_URL is not configured"); const client = await pool.connect(); try { await client.query("BEGIN"); const result = await fn(client); await client.query("COMMIT"); return result; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
async function withClient<T>(fn: (client: PoolClient) => Promise<T>): Promise<T> { if (!pool) throw new Error("DATABASE_URL is not configured"); const client = await pool.connect(); try { return await fn(client); } finally { client.release(); } }
async function requireAuth(request: Parameters<typeof authenticate>[0], reply: { code: (status: number) => { send: (body: unknown) => unknown } }): Promise<AuthContext | null> { try { const auth = await authenticate(request, pool); if (!auth) { reply.code(401).send(bearerChallenge()); return null; } return auth; } catch (error) { request.log.error(error); reply.code(503).send({ error: "Authentication service unavailable", code: "AUTH_UNAVAILABLE" }); return null; } }
function requireOrganization(auth: AuthContext, organizationId: string, reply: { code: (status: number) => { send: (body: unknown) => unknown } }): boolean { if (!canActForOrganization(auth, organizationId)) { reply.code(403).send({ error: "No verified membership for organization", code: "ORG_FORBIDDEN" }); return false; } return true; }
function requestedGeography(request: { query: unknown }): string | null { const q = request.query && typeof request.query === "object" ? request.query as Record<string, unknown> : {}; return typeof q.geographyId === "string" && q.geographyId.trim() ? q.geographyId.trim() : null; }
async function canReadGeography(client: PoolClient, auth: AuthContext, geographyId: string): Promise<boolean> { if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(geographyId)) return false; const result = await client.query<{ ok: boolean }>(`select exists(select 1 from organization_memberships om where om.identity_id=$1 and om.status='VERIFIED' and organization_has_geography_scope(om.organization_id,$2)) as ok`, [auth.identityId, geographyId]); return result.rows[0]?.ok === true; }
async function canWriteActivity(client: Pool | PoolClient, auth: AuthContext, activityId: string): Promise<boolean> { const result = await client.query<{ ok: boolean }>(`select exists(select 1 from activities a join organization_memberships om on om.organization_id=a.organization_id and om.identity_id=$2 and om.status='VERIFIED' where a.id=$1 and a.geography_id is not null and organization_has_geography_scope(om.organization_id,a.geography_id)) as ok`, [activityId, auth.identityId]); return result.rows[0]?.ok === true; }
async function canWriteGeography(client: Pool | PoolClient, auth: AuthContext, organizationId: string, geographyId: string): Promise<boolean> { if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(geographyId)) return false; const result = await client.query<{ ok: boolean }>(`select exists(select 1 from organization_memberships om where om.identity_id=$1 and om.organization_id=$2 and om.status='VERIFIED' and organization_has_geography_scope(om.organization_id,$3)) as ok`, [auth.identityId, organizationId, geographyId]); return result.rows[0]?.ok === true; }

app.get("/health", async (_request, reply) => { let database: "AVAILABLE" | "UNAVAILABLE" = "UNAVAILABLE"; if (pool) { try { await pool.query("select 1"); database = "AVAILABLE"; } catch {} } const healthy = database === "AVAILABLE"; return reply.code(healthy ? 200 : 503).send({ status: healthy ? "READY" : "DEGRADED", database, syntheticData: false }); });
app.get("/api/v1/status", async () => ({ service: "rupaykg-api", version: "0.1.0", sourceOfTruth: "postgresql", syntheticData: false }));
app.get("/api/v1/overview", async (request, reply) => {
  const auth = await requireAuth(request, reply); if (!auth || !pool) return;
  try {
    const organizationIds = [...new Set(auth.memberships.map(m => m.organization_id))];
    if (!organizationIds.length) return { source: "postgresql", syntheticData: false, counts: { activities: 0, measurements: 0, evidence: 0, approvedVerifications: 0, openObligations: 0, issuedOrActiveCredentials: 0, settledTransactions: 0 } };
    const [activities, measurements, evidence, verifications, obligations, credentials, settlements] = await Promise.all([
      query<{ count: string }>("select count(*)::text as count from activities where organization_id = any($1::uuid[])", [organizationIds]),
      query<{ count: string }>("select count(*)::text as count from measurements m join activities a on a.id=m.activity_id where a.organization_id = any($1::uuid[])", [organizationIds]),
      query<{ count: string }>("select count(*)::text as count from evidence e join activities a on a.id=e.activity_id where a.organization_id = any($1::uuid[])", [organizationIds]),
      query<{ count: string }>("select count(*)::text as count from verifications v join activities a on a.id=v.activity_id where a.organization_id = any($1::uuid[]) and v.decision = 'APPROVED'", [organizationIds]),
      query<{ count: string }>("select count(*)::text as count from obligations where organization_id = any($1::uuid[]) and status = 'OPEN'", [organizationIds]),
      query<{ count: string }>("select count(*)::text as count from credentials where issuer_organization_id = any($1::uuid[]) and status in ('ISSUED','ACTIVE','TRANSFERRED','RETIRED')", [organizationIds]),
      query<{ count: string }>("select count(*)::text as count from settlements where (payer_id = any($1::uuid[]) or payee_id = any($1::uuid[])) and status = 'SETTLED'", [organizationIds]),
    ]);
    return { source: "postgresql", syntheticData: false, counts: { activities: Number(activities[0]?.count ?? 0), measurements: Number(measurements[0]?.count ?? 0), evidence: Number(evidence[0]?.count ?? 0), approvedVerifications: Number(verifications[0]?.count ?? 0), openObligations: Number(obligations[0]?.count ?? 0), issuedOrActiveCredentials: Number(credentials[0]?.count ?? 0), settledTransactions: Number(settlements[0]?.count ?? 0) } };
  } catch (error) { request.log.error(error); return reply.code(503).send({ error: "Authoritative overview unavailable", syntheticData: false }); }
});
app.get("/api/v1/regulatory/sources", async (_request, reply) => { try { return { source: "postgresql", syntheticData: false, sources: await query("select id, authority, title, instrument, reference, published_on, effective_from, jurisdiction, source_url, verified_on, status, affected_module, notes from regulatory_sources order by effective_from desc nulls last, published_on desc") }; } catch (error) { return reply.code(503).send({ error: "Regulatory source catalog unavailable", syntheticData: false }); } });

app.get("/api/v1/geography/roots", async (request, reply) => { const auth = await requireAuth(request, reply); if (!auth || !pool) return; try { const rows = await pool.query(`select id,parent_id,kind,code,external_code,name,source,source_version,valid_from,valid_to,metadata from geography where parent_id is null order by name`); const visible: unknown[] = []; for (const row of rows.rows) if (await withClient(client => canReadGeography(client, auth, row.id))) visible.push(row); return { source: "postgresql", syntheticData: false, data: { geography: visible } }; } catch (error) { request.log.error(error); return reply.code(503).send({ error: "Authoritative geography unavailable", syntheticData: false }); } });
app.get("/api/v1/geography/children/:parentId", async (request, reply) => { const auth = await requireAuth(request, reply); if (!auth || !pool) return; try { const { parentId } = request.params as { parentId: string }; if (!await withClient(client => canReadGeography(client, auth, parentId))) return reply.code(403).send({ error: "Geography outside organization authorization scope", code: "GEOGRAPHY_FORBIDDEN" }); const rows = await pool.query("select id,parent_id,kind,code,external_code,name,source,source_version,valid_from,valid_to,metadata from geography where parent_id=$1 order by name", [parentId]); return { source: "postgresql", syntheticData: false, data: { geography: rows.rows } }; } catch (error) { request.log.error(error); return reply.code(503).send({ error: "Authoritative geography unavailable", syntheticData: false }); } });

app.post("/api/v1/operations/sync", async (request, reply) => { const auth = await requireAuth(request, reply); if (!auth) return; const body = bodyOf(request); const idempotencyKey = requiredString(body, "idempotencyKey"); const deviceId = requiredString(body, "deviceId"); const capturedAt = requiredString(body, "capturedAt"); if (!idempotencyKey || !deviceId || !capturedAt || !body.payload) return reply.code(400).send({ error: "idempotencyKey, deviceId, capturedAt and payload are required" }); if (Number.isNaN(Date.parse(capturedAt))) return reply.code(400).send({ error: "capturedAt must be an ISO date" }); try { const existing = await query<{ id: string; status: string; actor_identity_id: string }>("select id,status,actor_identity_id from operation_sync_envelopes where idempotency_key=$1", [idempotencyKey]); if (existing[0]) { if (existing[0].actor_identity_id !== auth.identityId) return reply.code(403).send({ error: "Idempotency key belongs to another identity", code: "IDEMPOTENCY_FORBIDDEN" }); return { source: "postgresql", syntheticData: false, replay: true, operation: existing[0] }; } const rows = await query<{ id: string; status: string }>("insert into operation_sync_envelopes (idempotency_key,actor_identity_id,device_id,client_sequence,captured_at,payload,payload_hash) values($1,$2,$3,$4,$5,$6,$7) returning id,status", [idempotencyKey,auth.identityId,deviceId,body.sequence ?? null,capturedAt,body.payload,body.payloadHash ?? null]); return reply.code(202).send({ source: "postgresql", syntheticData: false, replay: false, operation: rows[0] }); } catch (error) { request.log.error(error); return reply.code(503).send({ error: "Operation intake unavailable", syntheticData: false }); } });
app.post("/api/v1/resource-flows", async (request, reply) => { const auth = await requireAuth(request, reply); if (!auth) return; const body = bodyOf(request); const organizationId = requiredString(body,"organizationId"); const originType = requiredString(body,"originType"); const resourceForm = requiredString(body,"resourceForm"); const materialCode = requiredString(body,"materialCode"); const unit = requiredString(body,"unit"); const quantity = requiredPositiveNumber(body,"quantity"); if (!organizationId || !originType || !resourceForm || !materialCode || !unit || quantity === null) return reply.code(400).send({ error:"organizationId, originType, resourceForm, positive quantity and unit are required" }); if (!requireOrganization(auth,organizationId,reply)) return; const sourceGeographyId = requiredString(body,"sourceGeographyId"); const destinationGeographyId = requiredString(body,"destinationGeographyId"); if (!sourceGeographyId && !destinationGeographyId) return reply.code(400).send({ error:"At least one authorized sourceGeographyId or destinationGeographyId is required", code:"GEOGRAPHY_REQUIRED" }); try { if (sourceGeographyId && !await canWriteGeography(pool!,auth,organizationId,sourceGeographyId)) return reply.code(403).send({ error:"Source geography is outside organization authorization scope", code:"GEOGRAPHY_FORBIDDEN" }); if (destinationGeographyId && !await canWriteGeography(pool!,auth,organizationId,destinationGeographyId)) return reply.code(403).send({ error:"Destination geography is outside organization authorization scope", code:"GEOGRAPHY_FORBIDDEN" }); const rows = await query("insert into resource_flows (organization_id,origin_type,resource_form,material_code,declared_quantity,unit,source_geography_id,destination_geography_id) values($1,$2,$3,$4,$5,$6,$7,$8) returning *",[organizationId,originType,resourceForm,materialCode,quantity,unit,sourceGeographyId,destinationGeographyId]); return reply.code(201).send({source:"postgresql",syntheticData:false,resourceFlow:rows[0]}); } catch (error) { request.log.error(error); return reply.code(503).send({error:"Resource flow creation unavailable",syntheticData:false}); } });
app.post("/api/v1/activities/:activityId/measurements", async (request, reply) => { const auth=await requireAuth(request,reply);if(!auth)return;const {activityId}=request.params as {activityId:string};const body=bodyOf(request);const value=requiredPositiveNumber(body,"value"),unit=requiredString(body,"unit"),method=requiredString(body,"method"),source=requiredString(body,"source"),measuredAt=requiredString(body,"measuredAt");if(value===null||!unit||!method||!source||!measuredAt||Number.isNaN(Date.parse(measuredAt)))return reply.code(400).send({error:"positive value, unit, method, source and valid measuredAt are required"});try{if(!await canWriteActivity(pool!,auth,activityId))return reply.code(403).send({error:"Activity is outside organization authorization scope or has no authorized geography",code:"ACTIVITY_FORBIDDEN"});const rows=await query("insert into measurements(activity_id,value,unit,method,source,measured_at) values($1,$2,$3,$4,$5,$6) returning *",[activityId,value,unit,method,source,measuredAt]);return reply.code(201).send({source:"postgresql",syntheticData:false,measurement:rows[0]});}catch(error){request.log.error(error);return reply.code(503).send({error:"Measurement recording unavailable",syntheticData:false});}});

await registerValueRoutes(app, { pool, query, withTransaction, requireAuth, requireOrganization, requestedGeography });
await registerRegistryRoutes(app, { pool, query, withTransaction, requireAuth, requireOrganization, requestedGeography });
await registerSyncRoutes(app, { pool, query, withTransaction, requireAuth, requireOrganization, requestedGeography });
await registerWorkspaceRoutes(app, { pool, query, withTransaction, requireAuth, requireOrganization, requestedGeography });
await registerIntelligenceRoutes(app, { pool, query, withTransaction, requireAuth, requireOrganization, requestedGeography });

if (existsSync(webRoot)) {
  app.get("/*", async (_request, reply) => reply.sendFile("index.html"));
}

const port = Number(process.env.PORT ?? 3000);
const host = process.env.HOST ?? "0.0.0.0";
await app.listen({ port, host });
