-- Seed operational requirements after the authoritative source catalog exists.
-- RupayKG tracks evidence and provenance; statutory acceptance remains with
-- CPCB/SPCB/PCC/ULB/SEBI/BEE and other competent authorities.

insert into regulatory_requirements (regulatory_source_id,code,stakeholder_class,requirement_type,obligation,evidence_requirements,reporting_frequency,external_system,external_url,notes)
select s.id,v.code,v.stakeholder_class,v.requirement_type,v.obligation,v.evidence_requirements::jsonb,v.reporting_frequency,v.external_system,v.external_url,v.notes
from regulatory_sources s
join (values
('Plastic Waste Management Rules, 2016 and amendments','PWM-PIBO-PWP-REGISTRATION','PRODUCER_IMPORTER_BRAND_OWNER_PROCESSOR','REGISTRATION','Maintain applicable registration with the competent CPCB/SPCB/PCC EPR authority.','["legal_entity","authorization","registration_reference"]','ON_EVENT','CPCB Plastic EPR Portal','https://eprplastic.cpcb.gov.in/','RupayKG records statutory references and status; it does not create statutory registration.'),
('Plastic Waste Management Rules, 2016 and amendments','PWM-EPR-RETURN-CERTIFICATE','PRODUCER_IMPORTER_BRAND_OWNER_PROCESSOR','EPR','Track category-wise eligible processing evidence, EPR certificate references and required returns.','["verified_activity","measurement","evidence","verification","certificate_reference","return_reference"]','ANNUAL_OR_AS_NOTIFIED','CPCB Plastic EPR Portal','https://eprplastic.cpcb.gov.in/','Only certificates accepted by the statutory portal can satisfy statutory obligations.'),
('E-Waste (Management) Rules, 2022 and amendments','E-WASTE-REGISTRATION','PRODUCER_RECYCLER_REFURBISHER','REGISTRATION','Maintain applicable CPCB/SPCB/PCC registrations under the E-Waste EPR regime.','["legal_entity","registration_reference","authorization"]','ON_EVENT','CPCB E-Waste EPR Portal','https://eprewaste.cpcb.gov.in/','Portal registration and statutory acceptance remain authoritative externally.'),
('E-Waste (Management) Rules, 2022 and amendments','E-WASTE-EPR-RETURNS','PRODUCER_RECYCLER_REFURBISHER','EPR','Track EPR targets, eligible recycling evidence, certificate transactions and required returns.','["sales_or_introduction_data","verified_recycling","certificate_reference","return_reference"]','QUARTERLY_OR_AS_NOTIFIED','CPCB E-Waste EPR Portal','https://eprewaste.cpcb.gov.in/','Distinguish internal evidence from statutory portal acceptance.'),
('Battery Waste Management Rules, 2022 and amendments','BATTERY-EPR-REGISTRATION','PRODUCER_RECYCLER_REFURBISHER','REGISTRATION','Maintain applicable registration with CPCB and concerned SPCB/PCC as required by the Battery Waste Management Rules.','["legal_entity","registration_reference","authorization"]','ON_EVENT','CPCB Battery EPR Portal','https://eprbattery.cpcb.gov.in/','Battery EPR participation is controlled by the statutory portal.'),
('Battery Waste Management Rules, 2022 and amendments','BATTERY-EPR-TARGETS-RETURNS','PRODUCER_RECYCLER_REFURBISHER','EPR','Track collection/recycling targets, EPR credits/certificates and annual returns against the applicable schedule.','["market_introduction_data","verified_processing","certificate_reference","return_reference"]','ANNUAL_OR_AS_NOTIFIED','CPCB Battery EPR Portal','https://eprbattery.cpcb.gov.in/','Target calculations must use the applicable rule version and reporting period.'),
('Hazardous and Other Wastes (Management and Transboundary Movement) Rules, 2016 - Waste Tyre EPR','TYRE-EPR-REGISTRATION','TYRE_PRODUCER_RECYCLER_RETREADER','REGISTRATION','Maintain CPCB registration before carrying out regulated producer, recycler or retreader activity.','["legal_entity","registration_reference","authorization"]','ON_EVENT','CPCB Waste Tyre EPR Portal','https://eprtyres.cpcb.gov.in/','Statutory registration and certificate workflows remain external.'),
('Hazardous and Other Wastes (Management and Transboundary Movement) Rules, 2016 - Waste Tyre EPR','TYRE-EPR-CERTIFICATE','TYRE_PRODUCER_RECYCLER_RETREADER','EPR','Track recycling/retreading evidence and statutory EPR certificate references for producer fulfilment.','["verified_processing","invoice_reference","certificate_reference","return_reference"]','ANNUAL_OR_AS_NOTIFIED','CPCB Waste Tyre EPR Portal','https://eprtyres.cpcb.gov.in/','Only registered entities and certificates accepted by CPCB count for statutory fulfilment.'),
('Environment (Construction and Demolition) Waste Management Rules, 2025','CDW-REGISTRATION','CDW_PRODUCER_RECYCLER_COLLECTION_STORAGE','REGISTRATION','Track applicable registration and authorization for C&D waste participants.','["legal_entity","registration_reference","authorization"]','ON_EVENT','CPCB C&D Waste Management System','https://cdwm.cpcb.gov.in/','Applicability depends on the notified Rules and entity/activity profile.'),
('Environment (Construction and Demolition) Waste Management Rules, 2025','CDW-EPR-UTILISATION','CDW_PRODUCER_RECYCLER_ROAD_PROJECT','EPR','Track processed C&D quantities, EPR certificates and utilization submissions.','["verified_processing","quantity_measurement","certificate_reference","utilisation_reference"]','MONTHLY_OR_AS_NOTIFIED','CPCB C&D Waste Management System','https://cdwm.cpcb.gov.in/','Processed material must be linked to registered recyclers and accepted portal records where required.'),
('BRSR - Business Responsibility and Sustainability Reporting','BRSR-REPORTING','LISTED_ENTITY','ESG_REPORTING','Maintain traceable ESG metrics and disclosures for applicable BRSR reporting.','["source_activity","measurement","evidence","verification","methodology","approval"]','ANNUAL','SEBI','https://www.sebi.gov.in/sebi_data/attachdocs/may-2021/1620655793598.pdf','RupayKG is a data/provenance system, not the statutory filing authority.'),
('BRSR Core - Framework for assurance and ESG disclosures for value chain','BRSR-CORE-ASSURANCE','LISTED_ENTITY_ASSURANCE_PROVIDER','ESG_ASSURANCE','Track BRSR Core metrics, methodology, evidence lineage and independent assurance state for applicable entities.','["metric_definition","source_data","evidence","methodology","assurance_decision","assurance_provider"]','ANNUAL','SEBI','https://www.sebi.gov.in/legal/circulars/jul-2023/brsr-core-framework-for-assurance-and-esg-disclosures-for-value-chain_73854.html','Applicability and assurance scope follow the applicable SEBI framework.')
) as v(source_title,code,stakeholder_class,requirement_type,obligation,evidence_requirements,reporting_frequency,external_system,external_url,notes)
  on v.source_title=s.title
where not exists (select 1 from regulatory_requirements r where r.code=v.code);
