import { getAuth, onAuthStateChanged, signInWithRedirect, GoogleAuthProvider } from "firebase/auth";
import { getApps, getApp, initializeApp } from "firebase/app";
import "./styles.css";

type Membership = { organization_id: string; status: string; permissions?: string[]; can_write_esg?: boolean; can_assess_epr?: boolean };
type Session = { sessionToken: string; memberships: Membership[] };
type Workspace = { profiles: any[]; periods: any[]; wasteReports: any[]; eprReports: any[]; esgReports: any[]; jurisdictions: { id: string; name: string }[]; schemes: { id: string; code: string; name: string; authority: string; jurisdiction_id: string | null }[]; organizations: { organizationId: string; profileUpdate: boolean; periodCreate: boolean; wasteRecord: boolean; eprManage: boolean; esgWrite: boolean }[] };

const firebaseConfig = { apiKey: import.meta.env.VITE_FIREBASE_API_KEY, authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN, projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID, appId: import.meta.env.VITE_FIREBASE_APP_ID };
const firebaseApp = getApps().some((app) => app.name === "bwg-reporting") ? getApp("bwg-reporting") : initializeApp(firebaseConfig, "bwg-reporting");
const auth = getAuth(firebaseApp);
const mount = document.getElementById("bwg-reporting");
if (!mount) throw new Error("BWG reporting mount missing");
const root: HTMLElement = mount;
let session: Session | null = null;
let workspace: Workspace = { profiles: [], periods: [], wasteReports: [], eprReports: [], esgReports: [], jurisdictions: [], schemes: [], organizations: [] };
let message = "";
const value = (id: string) => (document.getElementById(id) as HTMLInputElement | HTMLSelectElement | null)?.value.trim() ?? "";
const num = (id: string) => Number(value(id));
const member = () => session?.memberships.find((m) => m.status === "VERIFIED") ?? null;
const capability = (key: keyof Workspace["organizations"][number]) => { const org = member(); return org ? Boolean(workspace.organizations.find((x) => x.organizationId === org.organization_id)?.[key]) : false; };
const esc = (v: unknown) => String(v ?? "").replace(/[&<>\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c] ?? c));

async function api(path: string, options: RequestInit = {}) {
  const r = await fetch(path, { ...options, headers: { ...(options.body ? { "Content-Type": "application/json" } : {}), ...(session ? { Authorization: `Bearer ${session.sessionToken}` } : {}), ...(options.headers ?? {}) } });
  const body = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error(body.error ?? `Request failed (${r.status})`);
  return body;
}

function render() {
  if (!session) {
    root.innerHTML = `<section class="compliance-card bwg-card"><div class="compliance-head"><div><p class="eyebrow">BULK WASTE GENERATOR</p><h2>EPR &amp; ESG reporting</h2><p>Authoritative reporting workspace. External submission or acceptance is never inferred.</p></div><span class="compliance-state">SIGN IN REQUIRED</span></div><button id="bwg-sign-in" type="button">Sign in to BWG workspace</button></section>`;
    root.querySelector("#bwg-sign-in")?.addEventListener("click", () => void signInWithRedirect(auth, new GoogleAuthProvider()));
    return;
  }
  const org = member();
  if (!org) { root.innerHTML = `<section class="compliance-card bwg-card"><div class="compliance-head"><div><p class="eyebrow">BULK WASTE GENERATOR</p><h2>EPR &amp; ESG reporting</h2></div><span class="compliance-state">VERIFICATION REQUIRED</span></div><p class="field-help">A verified organization membership is required.</p></section>`; return; }
  const periods = workspace.periods.map((p) => `<option value="${esc(p.id)}">${esc(p.period_start)} → ${esc(p.period_end)} · ${esc(p.reporting_basis)}</option>`).join("");
  const jurisdictions = workspace.jurisdictions.map((g) => `<option value="${esc(g.id)}">${esc(g.name)}</option>`).join("");
  const schemes = workspace.schemes.map((s) => `<option value="${esc(s.id)}">${esc(s.name)} · ${esc(s.code)} · ${esc(s.authority)}</option>`).join("");
  root.innerHTML = `<section class="compliance-card bwg-card" aria-labelledby="bwg-title"><div class="compliance-head"><div><p class="eyebrow">BULK WASTE GENERATOR</p><h2 id="bwg-title">EPR &amp; ESG reporting</h2><p>Backend-authoritative records only. CPCB submission or acceptance is never inferred.</p></div><span class="compliance-state">AUTHENTICATED</span></div>${message ? `<div class="resource-flow-state" role="status">${esc(message)}</div>` : ""}<div class="bwg-grid">
<form id="profile" class="esg-form"><h3>1. BWG applicability</h3><label>Authorized jurisdiction<select id="jurisdiction" required>${jurisdictions || `<option value="">No authorized geography available</option>`}</select></label><label>Establishment type<input id="etype" required placeholder="e.g. commercial facility"></label><div class="esg-form__row"><label>Floor area (sq.m.)<input id="area" required type="number" min="0" step="0.01"></label><label>Water (L/day)<input id="water" required type="number" min="0" step="0.01"></label></div><label>Waste generation (kg/day)<input id="dailywaste" required type="number" min="0" step="0.01"></label><button type="submit" ${capability("profileUpdate") ? "" : "disabled"}>Save profile</button></form>
<form id="period" class="esg-form"><h3>2. Reporting period</h3><div class="esg-form__row"><label>Start<input id="start" required type="date"></label><label>End<input id="end" required type="date"></label></div><label>Basis<select id="basis"><option value="SWM_2026">SWM 2026</option><option value="EPR">EPR</option><option value="ESG">ESG</option><option value="BRSR_VALUE_CHAIN">BRSR value chain</option></select></label><button type="submit" ${capability("periodCreate") ? "" : "disabled"}>Create period</button></form>
<form id="waste" class="esg-form"><h3>3. Waste report</h3><label>Period<select id="wperiod" required>${periods || `<option value="">Create a period first</option>`}</select></label><label>Waste stream<input id="stream" required placeholder="e.g. dry waste"></label><div class="esg-form__row"><label>Generated<input id="generated" required type="number" min="0" step="0.001"></label><label>Segregated<input id="segregated" type="number" min="0" step="0.001" value="0"></label></div><div class="esg-form__row"><label>Channelised<input id="channelized" type="number" min="0" step="0.001" value="0"></label><label>Processed<input id="processed" type="number" min="0" step="0.001" value="0"></label></div><label>Unit<input id="unit" value="kg" required></label><label>Verified evidence UUID<input id="wevidence" placeholder="Optional until evidence is available"></label><label>Approved verification UUID<input id="wverification" placeholder="Requires verified evidence"></label><button type="submit" ${capability("wasteRecord") && workspace.periods.length ? "" : "disabled"}>Record waste</button></form>
<form id="epr" class="esg-form"><h3>4. EPR report</h3><label>Period<select id="eperiod" required>${periods || `<option value="">Create a period first</option>`}</select></label><label>Authoritative EPR scheme<select id="scheme" required>${schemes || `<option value="">No verified EPR scheme available</option>`}</select></label><label>Category code<input id="category" required placeholder="Authoritative category code"></label><div class="esg-form__row"><label>Obligated<input id="obligated" required type="number" min="0" step="0.001"></label><label>Fulfilled<input id="fulfilled" required type="number" min="0" step="0.001"></label></div><label>Verified evidence UUID<input id="eevidence" placeholder="Optional until evidence is available"></label><label>Approved verification UUID<input id="everification" placeholder="Requires verified evidence"></label><button type="submit" ${capability("eprManage") && workspace.periods.length ? "" : "disabled"}>Record EPR</button><p class="field-help">Fulfilment may exceed an obligation. The API does not cap legitimate over-fulfilment.</p><p class="field-help">Internal authoritative report only; no CPCB submission or acceptance is claimed.</p></form>
<form id="esg" class="esg-form"><h3>5. ESG metric</h3><label>Period<select id="gperiod" required>${periods || `<option value="">Create a period first</option>`}</select></label><label>Metric code<input id="metric" required placeholder="Authoritative metric code"></label><div class="esg-form__row"><label>Scope<input id="scope" required placeholder="e.g. 1, 2, 3"></label><label>Unit<input id="gunit" required></label></div><label>Value<input id="gvalue" required type="number" min="0" step="any"></label><label>Verified evidence UUID<input id="gevidence" placeholder="Optional until evidence is available"></label><label>Approved verification UUID<input id="gverification" placeholder="Requires verified evidence"></label><button type="submit" ${capability("esgWrite") && workspace.periods.length ? "" : "disabled"}>Record ESG metric</button></form></div><div class="compliance-list"><h3>Authoritative records</h3><p class="field-help">Profiles: ${workspace.profiles.length} · periods: ${workspace.periods.length} · waste: ${workspace.wasteReports.length} · EPR: ${workspace.eprReports.length} · ESG: ${workspace.esgReports.length}</p></div></section>`;
  root.querySelector("#profile")?.addEventListener("submit", (e) => { e.preventDefault(); void save("/api/v1/bwg/profile", { organizationId: org.organization_id, jurisdictionId: value("jurisdiction"), establishmentType: value("etype"), floorAreaSqm: num("area"), waterConsumptionLpd: num("water"), wasteGenerationKgDay: num("dailywaste") }); });
  root.querySelector("#period")?.addEventListener("submit", (e) => { e.preventDefault(); void save("/api/v1/bwg/reporting-periods", { organizationId: org.organization_id, periodStart: value("start"), periodEnd: value("end"), reportingBasis: value("basis") }); });
  root.querySelector("#waste")?.addEventListener("submit", (e) => { e.preventDefault(); const id = value("wperiod"); void save(`/api/v1/bwg/reporting-periods/${encodeURIComponent(id)}/waste`, { wasteStream: value("stream"), generatedQuantity: num("generated"), segregatedQuantity: num("segregated"), channelizedQuantity: num("channelized"), processedQuantity: num("processed"), unit: value("unit"), evidenceId: value("wevidence") || undefined, verificationId: value("wverification") || undefined }); });
  root.querySelector("#epr")?.addEventListener("submit", (e) => { e.preventDefault(); const id = value("eperiod"); void save(`/api/v1/bwg/reporting-periods/${encodeURIComponent(id)}/epr`, { schemeId: value("scheme"), categoryCode: value("category"), obligatedQuantity: num("obligated"), fulfilledQuantity: num("fulfilled"), evidenceId: value("eevidence") || undefined, verificationId: value("everification") || undefined }); });
  root.querySelector("#esg")?.addEventListener("submit", (e) => { e.preventDefault(); const id = value("gperiod"); void save(`/api/v1/bwg/reporting-periods/${encodeURIComponent(id)}/esg`, { metricCode: value("metric"), scope: value("scope"), unit: value("gunit"), value: num("gvalue"), evidenceId: value("gevidence") || undefined, verificationId: value("gverification") || undefined }); });
}
async function load() { if (!session) return; const r = await api("/api/v1/workspaces/bwg"); workspace = r.data ?? workspace; render(); }
async function save(path: string, body: unknown) { try { message = ""; await api(path, { method: "POST", body: JSON.stringify(body) }); message = "Saved to PostgreSQL authoritatively."; await load(); } catch (e) { message = e instanceof Error ? e.message : "Authoritative write failed."; render(); } }

onAuthStateChanged(auth, async (user) => { if (!user) { session = null; render(); return; } try { if (!user.emailVerified) throw new Error("Verified email is required before BWG reporting access."); const token = await user.getIdToken(true); const exchanged = await api("/api/v1/auth/exchange", { method: "POST", body: JSON.stringify({ idToken: token }) }); session = { sessionToken: exchanged.sessionToken, memberships: exchanged.memberships ?? [] }; const me = await api("/api/v1/auth/me"); session.memberships = me.memberships ?? []; await load(); } catch (e) { session = null; message = e instanceof Error ? e.message : "BWG workspace unavailable."; render(); } });
render();
