import { getAuth, onAuthStateChanged, signInWithRedirect, GoogleAuthProvider } from "firebase/auth";
import { getApps, getApp, initializeApp } from "firebase/app";
import "./styles.css";

const config = { apiKey: import.meta.env.VITE_FIREBASE_API_KEY, authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN, projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID, appId: import.meta.env.VITE_FIREBASE_APP_ID };
const app = getApps().some((item) => item.name === "bwg-reporting") ? getApp("bwg-reporting") : initializeApp(config, "bwg-reporting");
const auth = getAuth(app);
const root = document.getElementById("bwg-reporting");
if (!root) throw new Error("BWG reporting mount missing");

type Membership = { organization_id: string; status: string; permissions?: string[] };
type Session = { sessionToken: string; memberships: Membership[] };
type Profile = { organization_id: string; jurisdiction_name?: string; floor_area_sqm: number; water_consumption_lpd: number; waste_generation_kg_day: number; establishment_type: string; applicability_status: string; };
type Period = { id: string; organization_id: string; period_start: string; period_end: string; reporting_basis: string; status: string; external_submission_status: string; };
type Workspace = { profiles: Profile[]; periods: Period[]; wasteReports: Array<Record<string, unknown>>; eprReports: Array<Record<string, unknown>>; esgReports: Array<Record<string, unknown>> };

let session: Session | null = null;
let workspace: Workspace = { profiles: [], periods: [], wasteReports: [], eprReports: [], esgReports: [] };
let message = "";
let error = "";
const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c] ?? c));
const api = async (path: string, options: RequestInit = {}) => { const response = await fetch(path, { ...options, headers: { "Content-Type": "application/json", ...(options.headers ?? {}), ...(session ? { Authorization: `Bearer ${session.sessionToken}` } : {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? `Request failed (${response.status})`); return body; };
const activeMembership = () => session?.memberships.find((m) => m.status === "VERIFIED") ?? null;
const canWrite = (permission: string) => activeMembership()?.permissions?.includes(permission) ?? false;

function render(): void {
  const profile = workspace.profiles[0];
  const activePeriod = workspace.periods[0];
  root.innerHTML = `<section class="compliance-card bwg-card" aria-labelledby="bwg-title">
    <div class="compliance-head"><div><p class="eyebrow">BULK WASTE GENERATOR</p><h2 id="bwg-title">EPR & ESG reporting</h2><p>Record authoritative BWG applicability, waste flows, EPR evidence and ESG metrics. Submission or acceptance is never inferred.</p></div><span class="compliance-state">${session ? "AUTHENTICATED" : "SIGN IN REQUIRED"}</span></div>
    ${message ? `<div class="resource-flow-state">${escapeHtml(message)}</div>` : ""}${error ? `<div class="resource-flow-state" role="alert">${escapeHtml(error)}</div>` : ""}
    ${!session ? `<button id="bwg-sign-in" type="button">Sign in to BWG workspace</button>` : !activeMembership() ? `<div class="field-help">A verified organization membership is required.</div>` : `
    <div class="bwg-grid">
      <form id="bwg-profile-form" class="esg-form"><h3>1. BWG applicability</h3><label>Jurisdiction ID<input id="bwg-jurisdiction" required placeholder="Authorized geography UUID"></label><label>Establishment type<input id="bwg-type" required placeholder="Office, hotel, hospital, campus…"></label><div class="esg-form__row"><label>Floor area (sq.m.)<input id="bwg-area" required type="number" min="0" step="0.01"></label><label>Water (L/day)<input id="bwg-water" required type="number" min="0" step="0.01"></label></div><label>Waste generation (kg/day)<input id="bwg-waste" required type="number" min="0" step="0.01"></label><button type="submit" ${canWrite("profile:update") ? "" : "disabled"}>Save authoritative profile</button>${profile ? `<p class="field-help">Current status: <strong>${escapeHtml(profile.applicability_status)}</strong> · ${escapeHtml(profile.jurisdiction_name ?? "authorized jurisdiction")}</p>` : ""}</form>
      <form id="bwg-period-form" class="esg-form"><h3>2. Reporting period</h3><div class="esg-form__row"><label>Start<input id="bwg-start" required type="date"></label><label>End<input id="bwg-end" required type="date"></label></div><label>Reporting basis<select id="bwg-basis"><option value="SWM_2026">SWM Rules 2026</option><option value="EPR">EPR</option><option value="ESG">ESG</option><option value="BRSR_VALUE_CHAIN">BRSR / value chain (where applicable)</option></select></label><button type="submit" ${canWrite("waste:record") ? "" : "disabled"}>Create reporting period</button>${activePeriod ? `<p class="field-help">Latest: ${escapeHtml(activePeriod.period_start)} → ${escapeHtml(activePeriod.period_end)} · ${escapeHtml(activePeriod.status)} · external submission: ${escapeHtml(activePeriod.external_submission_status)}</p>` : ""}</form>
      <form id="bwg-waste-form" class="esg-form"><h3>3. Waste report</h3><label>Reporting period<select id="bwg-waste-period" required>${workspace.periods.map((p) => `<option value="${escapeHtml(p.id)}">${escapeHtml(p.period_start)} → ${escapeHtml(p.period_end)} · ${escapeHtml(p.reporting_basis)}</option>`).join("") || "<option value="">Create a period first</option>"}</select></label><label>Waste stream<input id="bwg-stream" required placeholder="Dry / wet / plastic / organic…"></label><div class="esg-form__row"><label>Generated<input id="bwg-generated" required type="number" min="0" step="0.001"></label><label>Segregated<input id="bwg-segregated" type="number" min="0" step="0.001" value="0"></label></div><div class="esg-form__row"><label>Channelised<input id="bwg-channelized" type="number" min="0" step="0.001" value="0"></label><label>Processed<input id="bwg-processed" type="number" min="0" step="0.001" value="0"></label></div><label>Unit<input id="bwg-unit" required value="kg"></label><label>Verified evidence UUID <span class="esg-form__optional">optional</span><input id="bwg-waste-evidence"></label><label>Approved verification UUID <span class="esg-form__optional">optional</span><input id="bwg-waste-verification"></label><button type="submit" ${canWrite("waste:record") && workspace.periods.length ? "" : "disabled"}>Record waste report</button></form>
      <form id="bwg-epr-form" class="esg-form"><h3>4. EPR report</h3><label>Reporting period<select id="bwg-epr-period" required>${workspace.periods.map((p) => `<option value="${escapeHtml(p.id)}">${escapeHtml(p.period_start)} → ${escapeHtml(p.period_end)}</option>`).join("") || "<option value="">Create a period first</option>"}</select></label><label>EPR scheme UUID<input id="bwg-scheme" required placeholder="Authoritative epr_schemes UUID"></label><label>Category code<input id="bwg-category" required placeholder="Authoritative category code"></label><div class="esg-form__row"><label>Obligated quantity<input id="bwg-obligated" required type="number" min="0" step="0.001"></label><label>Fulfilled quantity<input id="bwg-fulfilled" required type="number" min="0" step="0.001"></label></div><label>Verified evidence UUID <span class="esg-form__optional">optional</span><input id="bwg-epr-evidence"></label><label>Approved verification UUID <span class="esg-form__optional">optional</span><input id="bwg-epr-verification"></label><button type="submit" ${canWrite("epr:manage") && workspace.periods.length ? "" : "disabled"}>Record EPR report</button><p class="field-help">This records an authoritative report only. It does not submit to CPCB or claim CPCB acceptance.</p></form>
      <form id="bwg-esg-form" class="esg-form"><h3>5. ESG metric</h3><label>Reporting period<select id="bwg-esg-period" required>${workspace.periods.map((p) => `<option value="${escapeHtml(p.id)}">${escapeHtml(p.period_start)} → ${escapeHtml(p.period_end)}</option>`).join("") || "<option value="">Create a period first</option>"}</select></label><label>Metric code<input id="bwg-metric" required placeholder="Authoritative metric code"></label><div class="esg-form__row"><label>Scope<input id="bwg-scope" required placeholder="1 / 2 / 3 / IMPACT"></label><label>Unit<input id="bwg-esg-unit" required placeholder="kg, kWh, tCO2e…"></label></div><label>Value<input id="bwg-value" required type="number" min="0" step="any"></label><label>Verified evidence UUID <span class="esg-form__optional">optional</span><input id="bwg-esg-evidence"></label><label>Approved verification UUID <span class="esg-form__optional">optional</span><input id="bwg-esg-verification"></label><button type="submit" ${canWrite("reports:read") && workspace.periods.length ? "" : "disabled"}>Record ESG metric</button></form>
    </div>
    <div class="compliance-list"><h3>Authoritative records</h3><p class="field-help">Profiles: ${workspace.profiles.length} · periods: ${workspace.periods.length} · waste reports: ${workspace.wasteReports.length} · EPR reports: ${workspace.eprReports.length} · ESG reports: ${workspace.esgReports.length}</p></div>`}`;
  root.querySelector("#bwg-sign-in")?.addEventListener("click", () => void signInWithRedirect(auth, new GoogleAuthProvider()));
  root.querySelector("#bwg-profile-form")?.addEventListener("submit", (event) => { event.preventDefault(); void saveProfile(); });
  root.querySelector("#bwg-period-form")?.addEventListener("submit", (event) => { event.preventDefault(); void createPeriod(); });
  root.querySelector("#bwg-waste-form")?.addEventListener("submit", (event) => { event.preventDefault(); void saveWaste(); });
  root.querySelector("#bwg-epr-form")?.addEventListener("submit", (event) => { event.preventDefault(); void saveEpr(); });
  root.querySelector("#bwg-esg-form")?.addEventListener("submit", (event) => { event.preventDefault(); void saveEsg(); });
}

async function load(): Promise<void> { if (!session) return; const response = await api("/api/v1/workspaces/bwg"); workspace = response.data ?? workspace; render(); }
const input = (id: string) => (document.getElementById(id) as HTMLInputElement)?.value.trim() ?? "";
const num = (id: string) => Number(input(id));
async function write(path: string, body: unknown): Promise<void> { error = ""; message = ""; try { await api(path, { method: "POST", body: JSON.stringify(body) }); message = "Saved to PostgreSQL authoritatively."; await load(); } catch (caught) { error = caught instanceof Error ? caught.message : "Authoritative write failed."; render(); } }
async function saveProfile() { await write("/api/v1/bwg/profile", { organizationId: activeMembership()?.organization_id, jurisdictionId: input("bwg-jurisdiction"), establishmentType: input("bwg-type"), floorAreaSqm: num("bwg-area"), waterConsumptionLpd: num("bwg-water"), wasteGenerationKgDay: num("bwg-waste") }); }
async function createPeriod() { await write("/api/v1/bwg/reporting-periods", { organizationId: activeMembership()?.organization_id, periodStart: input("bwg-start"), periodEnd: input("bwg-end"), reportingBasis: (document.getElementById("bwg-basis") as HTMLSelectElement)?.value }); }
async function saveWaste() { await write(`/api/v1/bwg/reporting-periods/${encodeURIComponent((document.getElementById("bwg-waste-period") as HTMLSelectElement)?.value ?? "")}/waste`, { wasteStream: input("bwg-stream"), generatedQuantity: num("bwg-generated"), segregatedQuantity: num("bwg-segregated"), channelizedQuantity: num("bwg-channelized"), processedQuantity: num("bwg-processed"), unit: input("bwg-unit"), evidenceId: input("bwg-waste-evidence") || undefined, verificationId: input("bwg-waste-verification") || undefined }); }
async function saveEpr() { await write(`/api/v1/bwg/reporting-periods/${encodeURIComponent((document.getElementById("bwg-epr-period") as HTMLSelectElement)?.value ?? "")}/epr`, { schemeId: input("bwg-scheme"), categoryCode: input("bwg-category"), obligatedQuantity: num("bwg-obligated"), fulfilledQuantity: num("bwg-fulfilled"), evidenceId: input("bwg-epr-evidence") || undefined, verificationId: input("bwg-epr-verification") || undefined }); }
async function saveEsg() { await write(`/api/v1/bwg/reporting-periods/${encodeURIComponent((document.getElementById("bwg-esg-period") as HTMLSelectElement)?.value ?? "")}/esg`, { metricCode: input("bwg-metric"), scope: input("bwg-scope"), unit: input("bwg-esg-unit"), value: num("bwg-value"), evidenceId: input("bwg-esg-evidence") || undefined, verificationId: input("bwg-esg-verification") || undefined }); }

onAuthStateChanged(auth, async (user) => { if (!user) { session = null; workspace = { profiles: [], periods: [], wasteReports: [], eprReports: [], esgReports: [] }; render(); return; } try { if (!user.emailVerified) throw new Error("Verified email is required before BWG reporting access."); const idToken = await user.getIdToken(true); const exchanged = await api("/api/v1/auth/exchange", { method: "POST", body: JSON.stringify({ idToken }) }); session = { sessionToken: exchanged.sessionToken, memberships: exchanged.memberships ?? [] }; const me = await api("/api/v1/auth/me"); session.memberships = me.memberships ?? []; await load(); } catch (caught) { session = null; error = caught instanceof Error ? caught.message : "BWG workspace unavailable."; render(); } });
render();
