import { getAuth, onAuthStateChanged } from "firebase/auth";
import { initializeApp } from "firebase/app";
import { NATIONAL_LANGUAGES, getPreferredLanguage, setPreferredLanguage, languageDirection } from "./multilingual-national";

const config = { apiKey: import.meta.env.VITE_FIREBASE_API_KEY, authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN, projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID, appId: import.meta.env.VITE_FIREBASE_APP_ID };
const root = document.getElementById("citizen-farmer-guided");
if (root && Object.values(config).every(Boolean)) {
  const auth = getAuth(initializeApp(config, "citizen-farmer-guided"));
  const orgKey = "rupaykg.activeOrganizationId";
  let sessionToken = "";
  let canRecord = false;
  let language = getPreferredLanguage();
  const copy: Record<string, Record<string, string>> = {
    "en-IN": { title: "Simple entry for farmers and citizens", intro: "Record a real activity without learning the technical platform. Your authoritative record is preserved underneath.", activity: "What did you do?", agricultural: "Agricultural waste", household: "Household waste", recyclable: "Recyclable material", organic: "Organic material", quantity: "How much?", unit: "Unit", kg: "kg", location: "Where?", submit: "Record activity", signIn: "Sign in with a verified stakeholder account to record", readonly: "Your account can view records but cannot create this activity.", success: "Activity recorded in the authoritative system.", language: "Language" },
    "hi-IN": { title: "किसान और नागरिकों के लिए आसान प्रविष्टि", intro: "तकनीकी जानकारी सीखे बिना वास्तविक गतिविधि दर्ज करें। आपका प्रामाणिक रिकॉर्ड सुरक्षित रहता है।", activity: "आपने क्या किया?", agricultural: "कृषि अपशिष्ट", household: "घरेलू कचरा", recyclable: "पुनर्चक्रण योग्य सामग्री", organic: "जैविक सामग्री", quantity: "कितना?", unit: "इकाई", kg: "किग्रा", location: "कहाँ?", submit: "गतिविधि दर्ज करें", signIn: "दर्ज करने के लिए सत्यापित हितधारक खाते से साइन इन करें", readonly: "आपका खाता रिकॉर्ड देख सकता है, लेकिन यह गतिविधि बना नहीं सकता।", success: "गतिविधि प्रामाणिक प्रणाली में दर्ज हो गई।", language: "भाषा" },
    "bn-IN": { title: "কৃষক ও নাগরিকদের জন্য সহজ প্রবেশ", intro: "প্রযুক্তিগত বিষয় না শিখেই বাস্তব কার্যকলাপ নথিভুক্ত করুন। আপনার প্রামাণিক রেকর্ড সংরক্ষিত থাকবে।", activity: "আপনি কী করেছেন?", agricultural: "কৃষি বর্জ্য", household: "গৃহস্থালির বর্জ্য", recyclable: "পুনর্ব্যবহারযোগ্য উপাদান", organic: "জৈব উপাদান", quantity: "কতটা?", unit: "একক", kg: "কেজি", location: "কোথায়?", submit: "কার্যকলাপ নথিভুক্ত করুন", signIn: "নথিভুক্ত করতে যাচাইকৃত স্টেকহোল্ডার অ্যাকাউন্টে সাইন ইন করুন", readonly: "আপনার অ্যাকাউন্ট রেকর্ড দেখতে পারে কিন্তু এই কার্যকলাপ তৈরি করতে পারে না।", success: "কার্যকলাপ প্রামাণিক সিস্টেমে নথিভুক্ত হয়েছে।", language: "ভাষা" },
    "mr-IN": { title: "शेतकरी आणि नागरिकांसाठी सोपी नोंद", intro: "तांत्रिक माहिती न शिकता प्रत्यक्ष कामाची नोंद करा. तुमची अधिकृत नोंद सुरक्षित राहते.", activity: "तुम्ही काय केले?", agricultural: "कृषी कचरा", household: "घरगुती कचरा", recyclable: "पुनर्वापरयोग्य साहित्य", organic: "सेंद्रिय साहित्य", quantity: "किती?", unit: "एकक", kg: "किलो", location: "कुठे?", submit: "क्रियाकलाप नोंदवा", signIn: "नोंद करण्यासाठी सत्यापित हितधारक खात्याने साइन इन करा", readonly: "तुमचे खाते नोंदी पाहू शकते पण ही क्रिया तयार करू शकत नाही.", success: "क्रियाकलाप अधिकृत प्रणालीत नोंदवला गेला.", language: "भाषा" },
    "gu-IN": { title: "ખેડૂતો અને નાગરિકો માટે સરળ નોંધ", intro: "તકનીકી જ્ઞાન વિના વાસ્તવિક પ્રવૃત્તિ નોંધો. તમારો અધિકૃત રેકોર્ડ સુરક્ષિત રહેશે.", activity: "તમે શું કર્યું?", agricultural: "કૃષિ કચરો", household: "ઘરેલું કચરો", recyclable: "પુનઃચક્રિત સામગ્રી", organic: "સજીવ સામગ્રી", quantity: "કેટલું?", unit: "એકમ", kg: "કિગ્રા", location: "ક્યાં?", submit: "પ્રવૃત્તિ નોંધો", signIn: "નોંધ કરવા ચકાસાયેલ હિતધારક ખાતાથી સાઇન ઇન કરો", readonly: "તમારું ખાતું રેકોર્ડ જોઈ શકે છે પરંતુ આ પ્રવૃત્તિ બનાવી શકતું નથી.", success: "પ્રવૃત્તિ અધિકૃત સિસ્ટમમાં નોંધાઈ ગઈ.", language: "ભાષા" },
    "ta-IN": { title: "விவசாயிகள் மற்றும் குடிமக்களுக்கான எளிய பதிவு", intro: "தொழில்நுட்பத்தை அறியாமல் உண்மையான செயல்பாட்டைப் பதிவு செய்யுங்கள். உங்கள் அதிகாரப்பூர்வ பதிவு பாதுகாக்கப்படும்.", activity: "நீங்கள் என்ன செய்தீர்கள்?", agricultural: "விவசாயக் கழிவு", household: "வீட்டு கழிவு", recyclable: "மறுசுழற்சி பொருள்", organic: "கரிமப் பொருள்", quantity: "எவ்வளவு?", unit: "அலகு", kg: "கிலோ", location: "எங்கே?", submit: "செயல்பாட்டைப் பதிவு செய்யவும்", signIn: "பதிவு செய்ய சரிபார்க்கப்பட்ட பங்குதாரர் கணக்கில் உள்நுழையவும்", readonly: "உங்கள் கணக்கு பதிவுகளைப் பார்க்கலாம்; இந்தச் செயல்பாட்டை உருவாக்க முடியாது.", success: "செயல்பாடு அதிகாரப்பூர்வ அமைப்பில் பதிவு செய்யப்பட்டது.", language: "மொழி" },
    "te-IN": { title: "రైతులు మరియు పౌరుల కోసం సులభమైన నమోదు", intro: "సాంకేతికత నేర్చుకోకుండా నిజమైన కార్యకలాపాన్ని నమోదు చేయండి. మీ అధికారిక రికార్డు భద్రంగా ఉంటుంది.", activity: "మీరు ఏమి చేశారు?", agricultural: "వ్యవసాయ వ్యర్థాలు", household: "గృహ వ్యర్థాలు", recyclable: "రీసైకిల్ చేయగల పదార్థం", organic: "సేంద్రీయ పదార్థం", quantity: "ఎంత?", unit: "యూనిట్", kg: "కిలో", location: "ఎక్కడ?", submit: "కార్యకలాపాన్ని నమోదు చేయండి", signIn: "నమోదు చేయడానికి ధృవీకరించిన భాగస్వామి ఖాతాతో సైన్ ఇన్ చేయండి", readonly: "మీ ఖాతా రికార్డులను చూడగలదు కానీ ఈ కార్యకలాపాన్ని సృష్టించలదు.", success: "కార్యకలాపం అధికారిక వ్యవస్థలో నమోదైంది.", language: "భాష" }
  };
  const t = (key: string) => copy[language]?.[key] ?? copy["en-IN"][key] ?? key;
  const languageOptions = NATIONAL_LANGUAGES.map(item => `<option value="${item.code}">${item.nativeLabel} · ${item.label}</option>`).join("");
  root.innerHTML = `<section class="resource-flow-card citizen-guided-card" aria-label="${t("title")}"><div class="resource-flow-head"><div><p class="eyebrow">RUPAYKG · CITIZEN / FARMER</p><h2 data-title></h2><p data-intro></p></div><label class="form-field language-field"><span data-language-label></span><select data-language>${languageOptions}</select></label></div><form data-form><div class="resource-flow-grid"><label class="form-field"><span data-activity></span><select name="kind" required><option value="AGRICULTURAL">${t("agricultural")}</option><option value="HOUSEHOLD">${t("household")}</option><option value="RECYCLABLE">${t("recyclable")}</option><option value="ORGANIC">${t("organic")}</option></select></label><label class="form-field"><span data-quantity></span><input name="quantity" type="number" min="0.000001" step="any" required inputmode="decimal" /></label><label class="form-field"><span data-unit></span><select name="unit"><option value="kg">${t("kg")}</option><option value="tonne">tonne</option></select></label><label class="form-field"><span data-location></span><select name="geography"><option value="">—</option></select></label></div><div class="resource-flow-actions"><button type="submit" data-submit></button></div><p class="field-help" data-message></p></form></section>`;
  const form = root.querySelector<HTMLFormElement>("[data-form]")!; const submit = root.querySelector<HTMLButtonElement>("[data-submit]")!; const message = root.querySelector<HTMLElement>("[data-message]")!; const lang = root.querySelector<HTMLSelectElement>("[data-language]")!; const kind = form.elements.namedItem("kind") as HTMLSelectElement; const geo = form.elements.namedItem("geography") as HTMLSelectElement;
  const organizationHeaders = (): Record<string, string> => { const id = localStorage.getItem(orgKey) || ""; return id ? { "x-rupaykg-organization-id": id } : {}; };
  const applyLanguage = () => { document.documentElement.lang = language; document.documentElement.dir = languageDirection(language); lang.value = language; root?.querySelector<HTMLElement>("[data-title]")!.replaceChildren(document.createTextNode(t("title"))); root?.querySelector<HTMLElement>("[data-intro]")!.replaceChildren(document.createTextNode(t("intro"))); ["activity","quantity","unit","location","language-label"].forEach(key => { const node = root.querySelector<HTMLElement>(`[data-${key}]`); if (node) node.textContent = t(key === "language-label" ? "language" : key); }); submit.textContent = t("submit"); kind.options[0].textContent=t("agricultural"); kind.options[1].textContent=t("household"); kind.options[2].textContent=t("recyclable"); kind.options[3].textContent=t("organic"); form.elements.namedItem("unit") instanceof HTMLSelectElement && ((form.elements.namedItem("unit") as HTMLSelectElement).options[0].textContent=t("kg")); message.textContent = canRecord ? "" : t("signIn"); };
  async function exchange() { const user=auth.currentUser; if(!user||!user.emailVerified){sessionToken="";canRecord=false;submit.disabled=true;message.textContent=t("signIn");return;} try { const ex=await fetch("/api/v1/auth/exchange",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({idToken:await user.getIdToken(true)})}); const body=await ex.json(); if(!ex.ok) throw new Error(body?.error||"Session exchange failed"); sessionToken=body.sessionToken; const memberships=Array.isArray(body.memberships)?body.memberships.filter((m:any)=>m.status==="VERIFIED"):[]; const current=localStorage.getItem(orgKey); const membership=memberships.find((m:any)=>m.organization_id===current)||memberships[0]; if(membership?.organization_id)localStorage.setItem(orgKey,membership.organization_id); const me=await fetch("/api/v1/auth/me",{headers:{Authorization:`Bearer ${sessionToken}`,Accept:"application/json",...organizationHeaders()}}); const meBody=await me.json(); if(!me.ok) throw new Error(meBody?.error||"Unable to load membership"); const active=meBody.memberships?.find((m:any)=>m.status==="VERIFIED"&&(m.organization_id===localStorage.getItem(orgKey))); canRecord=Array.isArray(active?.permissions)&&active.permissions.includes("waste:record"); submit.disabled=!canRecord; await loadGeography(); message.textContent=canRecord?"":t("readonly"); } catch(error){sessionToken="";canRecord=false;submit.disabled=true;message.textContent=error instanceof Error?error.message:t("signIn");} }
  async function loadGeography(){ if(!sessionToken)return; const r=await fetch("/api/v1/geography/roots",{headers:{Authorization:`Bearer ${sessionToken}`,Accept:"application/json",...organizationHeaders()}}); const b=await r.json(); if(!r.ok)return; geo.innerHTML=`<option value="">—</option>`+(b?.data?.geography||[]).map((g:any)=>`<option value="${String(g.id).replace(/[&<>\"]/g,"")}">${String(g.name).replace(/[&<>\"]/g,"")} · ${String(g.kind).replace(/[&<>\"]/g,"")}</option>`).join(""); }
  form.addEventListener("submit",async e=>{e.preventDefault();if(!canRecord||!sessionToken)return; const data=new FormData(form); const geographyId=String(data.get("geography")||""); if(!geographyId){message.textContent=t("location");return;} submit.disabled=true; try { const r=await fetch("/api/v1/resource-flows",{method:"POST",headers:{Authorization:`Bearer ${sessionToken}`,"Content-Type":"application/json",Accept:"application/json",...organizationHeaders()},body:JSON.stringify({organizationId:localStorage.getItem(orgKey),originType:String(data.get("kind")),resourceForm:String(data.get("kind")),materialCode:`CITIZEN_${String(data.get("kind"))}`,quantity:Number(data.get("quantity")),unit:String(data.get("unit")),sourceGeographyId:geographyId})}); const b=await r.json(); if(!r.ok)throw new Error(b?.error||`Unable to record (${r.status})`); message.textContent=t("success"); form.reset(); window.dispatchEvent(new CustomEvent("rupaykg:resource-flow-created")); } catch(error){message.textContent=error instanceof Error?error.message:"Unable to record activity";} finally {submit.disabled=!canRecord;} });
  lang.addEventListener("change",()=>{language=setPreferredLanguage(lang.value);applyLanguage();}); window.addEventListener("rupaykg:language-changed",(event:any)=>{language=event.detail?.code||getPreferredLanguage();applyLanguage();}); onAuthStateChanged(auth,()=>void exchange()); applyLanguage();
} else if(root){root.textContent="";}
