import { getAuth, onAuthStateChanged } from "firebase/auth";
import { initializeApp } from "firebase/app";
import "./styles.css";

type Obligation={id:string;organization_id:string;organization_name:string;jurisdiction_id:string|null;jurisdiction_name:string|null;obligation_type:string;period_start:string;period_end:string;required_quantity:number|string;status:string};
type Me={memberships:Array<{organization_id:string;status:string}>};
type ApiInit=RequestInit;
const firebaseConfig={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const firebaseConfigured=Object.values(firebaseConfig).every(Boolean);
const firebaseAuth=firebaseConfigured?getAuth(initializeApp(firebaseConfig)):null;
async function api<T>(path:string,token="",init:ApiInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set("Accept","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(path,{...init,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error??`Request failed (${response.status})`);return body as T;}
function text(value:unknown){return value===null||value===undefined||value===""?"—":String(value);}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleDateString();}

const root=document.getElementById("compliance-assessment");
if(root&&firebaseAuth){
  const render=(state:{status:string;message:string;obligations:Obligation[]})=>{root.innerHTML=`<section class="compliance-card"><div class="compliance-head"><div><p class="eyebrow">AUTHORITATIVE COMPLIANCE</p><h2>EPR obligation assessment</h2><p>Assess an existing obligation against eligible, verified EPR credits through the production API. No quantities or obligation state are synthesized in the browser.</p></div><span class="compliance-state">${state.status}</span></div>${state.message?`<div class="resource-flow-state">${state.message}</div>`:""}<div class="compliance-list">${state.obligations.length?state.obligations.map(obligation=>`<article class="compliance-row"><div><strong>${text(obligation.obligation_type)}</strong><span>${text(obligation.organization_name)} · ${text(obligation.jurisdiction_name)} · ${formatDate(obligation.period_start)} – ${formatDate(obligation.period_end)}</span><small>Status: ${text(obligation.status)} · Required quantity: ${text(obligation.required_quantity)}</small></div><button data-assess="${obligation.id}">Assess obligation</button></article>`).join(""):"<div class="empty">No authorized obligations are available for assessment.</div>"}</div></section>`;root.querySelectorAll<HTMLButtonElement>("[data-assess]").forEach(button=>button.addEventListener("click",()=>void assess(button.dataset.assess!,state)));};
  const assess=async(id:string,state:{status:string;message:string;obligations:Obligation[]})=>{const button=root.querySelector<HTMLButtonElement>(`[data-assess="${id}"]`);if(button)button.disabled=true;try{const user=await firebaseAuth.currentUser;if(!user||!user.emailVerified)throw new Error("Verified Firebase sign-in is required.");const idToken=await user.getIdToken(true);const session=await api<{sessionToken:string}>("/api/v1/auth/exchange","",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken})});const result=await api<{assessment?:{status?:string;requiredQuantity?:number|string}}>(`/api/v1/epr/obligations/${id}/assess`,session.sessionToken,{method:"POST"});state.message=`Authoritative assessment completed: ${text(result.assessment?.status)} · required quantity ${text(result.assessment?.requiredQuantity)}`;const workspace=await api<{data:{obligations:Obligation[]}}>("/api/v1/workspaces/compliance",session.sessionToken);state.obligations=workspace.data.obligations??[];state.status="READY";}catch(error){state.message=error instanceof Error?error.message:"Compliance assessment failed.";}finally{render(state);}};
  const boot=async()=>{if(!firebaseConfigured){render({status:"UNAVAILABLE",message:"Firebase authentication is not configured for this deployment.",obligations:[]});return;}render({status:"CONNECTING",message:"Waiting for authenticated organization context…",obligations:[]});const user=firebaseAuth.currentUser;if(user){await load(user);}};
  const load=async(user:import("firebase/auth").User)=>{try{if(!user.emailVerified)throw new Error("Verify your email address before using compliance assessment.");const idToken=await user.getIdToken(true);const session=await api<{sessionToken:string}>("/api/v1/auth/exchange","",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken})});const me=await api<Me>("/api/v1/auth/me",session.sessionToken);if(!me.memberships.some(m=>m.status==="VERIFIED"))throw new Error("A verified organization membership is required.");const workspace=await api<{data:{obligations:Obligation[]}}>("/api/v1/workspaces/compliance",session.sessionToken);render({status:"READY",message:"Assessments use the authoritative obligation and verified-credit records.",obligations:workspace.data.obligations??[]});}catch(error){render({status:"UNAVAILABLE",message:error instanceof Error?error.message:"Unable to load authoritative compliance data.",obligations:[]});}};
  onAuthStateChanged(firebaseAuth,user=>{if(user)void load(user);else render({status:"SIGN IN REQUIRED",message:"Sign in to load authorized compliance obligations.",obligations:[]});});
  void boot();
}
