import { getAuth, onAuthStateChanged, type User } from "firebase/auth";
import { initializeApp } from "firebase/app";
import "./styles.css";

type Obligation={epr_obligation_id:string;scheme_id:string;scheme_code:string;scheme_name:string;category_code:string;target_quantity:number|string;fulfilled_quantity:number|string;status:string;period_start:string;period_end:string;jurisdiction_name?:string|null};
type EprReturn={id:string;scheme_code:string;scheme_name:string;obligation_id:string;period_start:string;period_end:string;return_type:string;reported_quantity:number|string;fulfilled_quantity:number|string;status:string;external_reference?:string|null;evidence_id?:string|null;verification_id?:string|null};
type Evidence={id:string;status:string;evidence_type:string};
type Verification={id:string;evidence_id:string;decision:string};
type Exchange={sessionToken:string};
const config={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const auth=Object.values(config).every(Boolean)?getAuth(initializeApp(config,"epr-return-lifecycle")):null;
const root=document.getElementById("epr-return-lifecycle");
const orgKey="rupaykg.activeOrganizationId";
const api=async<T>(path:string,token:string,init:RequestInit={}):Promise<T>=>{const headers=new Headers(init.headers);headers.set("Accept","application/json");headers.set("Authorization",`Bearer ${token}`);const org=localStorage.getItem(orgKey);if(org)headers.set("X-RupayKG-Organization-Id",org);const r=await fetch(path,{...init,headers});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error??`Request failed (${r.status})`);return b as T};
const esc=(v:unknown)=>String(v??"—").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]??c));
let token="";let obligations:Obligation[]=[];let returns:EprReturn[]=[];let evidence:Evidence[]=[];let verifications:Verification[]=[];let message="";
const session=async(user:User)=>{const idToken=await user.getIdToken(true);const result=await api<Exchange>("/api/v1/auth/exchange","",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken})});token=result.sessionToken;return token};
async function load(user:User){if(!user.emailVerified)throw new Error("Verify your email before using statutory EPR returns.");await session(user);const [o,r,m]=await Promise.all([api<{obligations:Obligation[]}>("/api/v1/epr/obligations",token),api<{returns:EprReturn[]}>("/api/v1/epr/returns",token),api<{data:{evidence:Evidence[];verifications:Verification[]}}>("/api/v1/workspaces/mrv",token)]);obligations=o.obligations??[];returns=r.returns??[];evidence=m.data?.evidence??[];verifications=m.data?.verifications??[];render();}
function render(){if(!root)return;const verifiedEvidence=evidence.filter(e=>e.status==="VERIFIED");const approved=verifications.filter(v=>v.decision==="APPROVED");root.innerHTML=`<section class="compliance-card epr-return-card"><div class="compliance-head"><div><p class="eyebrow">STATUTORY EPR LIFECYCLE</p><h2>EPR return & reconciliation</h2><p>Create a draft return, bind it to an authoritative EPR obligation, submit only with verified evidence and approved verification, then record the external portal reference.</p></div><span class="compliance-state">${esc(message||"AUTHORITATIVE")}</span></div><div class="compliance-list"><div class="compliance-row"><div style="width:100%"><strong>New statutory return</strong><div class="epr-return-form"><select id="epr-obligation"><option value="">Select EPR obligation</option>${obligations.map(o=>`<option value="${esc(o.epr_obligation_id)}">${esc(o.scheme_code)} · ${esc(o.category_code)} · ${esc(o.period_start)}–${esc(o.period_end)} · remaining ${Math.max(Number(o.target_quantity)-Number(o.fulfilled_quantity),0)}</option>`).join("")}</select><input id="epr-quantity" type="number" min="0.000001" step="0.000001" placeholder="Reported quantity"/><input id="epr-type" value="ANNUAL_RETURN" aria-label="Return type"/><button id="epr-create">Create draft</button></div></div></div>${returns.length?returns.map(r=>`<article class="compliance-row"><div><strong>${esc(r.scheme_code)} · ${esc(r.return_type)}</strong><span>${esc(r.period_start)} – ${esc(r.period_end)} · reported ${esc(r.reported_quantity)} · fulfilled ${esc(r.fulfilled_quantity)}</span><small>Status: ${esc(r.status)}${r.external_reference?` · External reference: ${esc(r.external_reference)}`:""}</small>${r.status==="DRAFT"||r.status==="REJECTED"?`<div class="epr-return-form"><select data-evidence="${esc(r.id)}"><option value="">Verified evidence</option>${verifiedEvidence.map(e=>`<option value="${esc(e.id)}">${esc(e.evidence_type)} · ${esc(e.id)}</option>`).join("")}</select><select data-verification="${esc(r.id)}"><option value="">Approved verification</option>${approved.filter(v=>verifiedEvidence.some(e=>e.id===v.evidence_id)).map(v=>`<option value="${esc(v.id)}">${esc(v.id)}</option>`).join("")}</select><button data-submit="${esc(r.id)}">Submit return</button></div>`:""}${["SUBMITTED","ACCEPTED","COMPLETED"].includes(r.status)?`<div class="epr-return-form"><input data-reference="${esc(r.id)}" placeholder="CPCB / external portal reference" value="${esc(r.external_reference??"")}"/><button data-record="${esc(r.id)}">Record external reference</button></div>`:""}</div></article>`).join(""):"<div class=\"empty\">No statutory EPR returns recorded for the active organization.</div>"}</div></section>`;
root.querySelector<HTMLButtonElement>("#epr-create")?.addEventListener("click",()=>void createDraft());root.querySelectorAll<HTMLButtonElement>("[data-submit]").forEach(b=>b.addEventListener("click",()=>void submitReturn(b.dataset.submit!)));root.querySelectorAll<HTMLButtonElement>("[data-record]").forEach(b=>b.addEventListener("click",()=>void recordReference(b.dataset.record!)));}
async function createDraft(){try{const id=(root?.querySelector("#epr-obligation") as HTMLSelectElement)?.value;const quantity=Number((root?.querySelector("#epr-quantity") as HTMLInputElement)?.value);const type=(root?.querySelector("#epr-type") as HTMLInputElement)?.value.trim()||"ANNUAL_RETURN";const o=obligations.find(x=>x.epr_obligation_id===id);if(!o||!Number.isFinite(quantity)||quantity<=0)throw new Error("Select an obligation and enter a positive quantity.");await api("/api/v1/epr/returns",token,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:localStorage.getItem(orgKey),schemeId:o.scheme_id,obligationId:o.epr_obligation_id,periodStart:o.period_start,periodEnd:o.period_end,returnType:type,reportedQuantity:quantity})});message="DRAFT CREATED";const user=auth?.currentUser;if(user)await load(user);}catch(e){message=e instanceof Error?e.message:"Unable to create draft";render();}}
async function submitReturn(id:string){try{const ev=(root?.querySelector(`[data-evidence="${id}"]`) as HTMLSelectElement)?.value;const vr=(root?.querySelector(`[data-verification="${id}"]`) as HTMLSelectElement)?.value;if(!ev||!vr)throw new Error("Select verified evidence and approved verification.");await api(`/api/v1/epr/returns/${id}/submit`,token,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({evidenceId:ev,verificationId:vr})});message="SUBMITTED — external CPCB submission remains separate";const user=auth?.currentUser;if(user)await load(user);}catch(e){message=e instanceof Error?e.message:"Unable to submit return";render();}}
async function recordReference(id:string){try{const reference=(root?.querySelector(`[data-reference="${id}"]`) as HTMLInputElement)?.value.trim();if(!reference)throw new Error("Enter the external portal reference.");await api(`/api/v1/epr/returns/${id}/external-reference`,token,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({externalReference:reference})});message="EXTERNAL REFERENCE RECORDED";const user=auth?.currentUser;if(user)await load(user);}catch(e){message=e instanceof Error?e.message:"Unable to record external reference";render();}}
if(root&&auth){onAuthStateChanged(auth,user=>{if(user)void load(user).catch(e=>{message=e instanceof Error?e.message:"Compliance unavailable";render();});else{message="SIGN IN REQUIRED";render();}});window.addEventListener("storage",e=>{if(e.key===orgKey&&auth.currentUser)void load(auth.currentUser);});}
