import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { createUserWithEmailAndPassword, getAuth, sendEmailVerification, setPersistence, signInWithEmailAndPassword, signOut, browserSessionPersistence, updateProfile } from "firebase/auth";
import { initializeApp } from "firebase/app";
import "./styles.css";

type Health={status:"READY"|"DEGRADED";database:"AVAILABLE"|"UNAVAILABLE";syntheticData:boolean};
type RegulatorySource={id:string;authority:string;title:string;instrument:string;reference:string;jurisdiction:string;status:string};
type Workspace={source:string;syntheticData:boolean;data?:Record<string,unknown>;[key:string]:unknown};
type WorkspaceKey="mrv"|"compliance"|"carbon"|"registry"|"settlement"|"resource-flows"|"intelligence";
type Membership={organization_id:string;role_id:string;status:string;role_name:string;organization_name:string;organization_type:string};
type Application={id:string;organization_id:string;requested_role_key:string;requested_organization_type:string;geography_id?:string|null;status:string;created_at:string;reviewed_at?:string|null;applicant_note?:string|null};
type Me={identity:{id:string;display_name:string;email?:string|null;status:string}|null;memberships:Membership[];applications:Application[]};
type ReviewApplication=Application&{applicant_identity_id:string;applicant_name:string;applicant_email?:string|null;organization_name:string;organization_type:string};
type ApiInit=RequestInit & {token?:string};

const firebaseConfig={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const firebaseConfigured=Object.values(firebaseConfig).every(Boolean);
const firebaseAuth=firebaseConfigured?getAuth(initializeApp(firebaseConfig)):null;
if(firebaseAuth) void setPersistence(firebaseAuth,browserSessionPersistence);
const roleLabels:Record<string,string>={citizen:"Citizen / household",farmer:"Farmer / rural producer",safai_mitra:"Waste collection worker",fpo:"FPO / rural enterprise",municipal_admin:"ULB / municipal authority",municipal_generator:"Municipal / bulk generator",aggregator:"Aggregator / transporter",processor:"MRF / recycler / processor",industry_generator:"Industrial generator",commercial_generator:"Commercial generator",institution_generator:"Institutional generator",PROJECT_OWNER:"Carbon project owner",ACVA_USER:"ACVA user",ccc_buyer:"Carbon / ESG buyer",epr_partner:"EPR partner",csr_partner:"CSR / ESG partner",regulator:"Regulator / public authority"};
const workspaces:Array<{key:WorkspaceKey;label:string;path:string;collection:string}>= [{key:"mrv",label:"MRV",path:"/api/v1/workspaces/mrv",collection:"activities"},{key:"compliance",label:"Compliance",path:"/api/v1/workspaces/compliance",collection:"obligations"},{key:"carbon",label:"Carbon",path:"/api/v1/workspaces/carbon",collection:"calculations"},{key:"registry",label:"Registry",path:"/api/v1/workspaces/registry",collection:"credentials"},{key:"settlement",label:"Settlement",path:"/api/v1/workspaces/settlement",collection:"settlements"},{key:"resource-flows",label:"Resource flows",path:"/api/v1/workspaces/resource-flows",collection:"resourceFlows"},{key:"intelligence",label:"Intelligence",path:"/api/v1/workspaces/intelligence",collection:"findings"}];
const labels={activities:"Activities",measurements:"Measurements",evidence:"Evidence",approvedVerifications:"Approved verification",openObligations:"Open obligations",issuedOrActiveCredentials:"Credentials",settledTransactions:"Settled transactions"};
class ApiError extends Error{status:number;code?:string;constructor(message:string,status:number,code?:string){super(message);this.status=status;this.code=code;}}
async function api<T>(path:string,token="",init:ApiInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set("Accept","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(path,{...init,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new ApiError(body?.error??`Request failed (${response.status})`,response.status,body?.code);return body as T;}
async function health():Promise<Health>{const response=await fetch("/health",{headers:{Accept:"application/json"}});const body=await response.json().catch(()=>({}));if(response.status!==200&&response.status!==503)throw new Error(body?.error??`Health check failed (${response.status})`);return body as Health;}
function value(v:unknown){if(v===null||v===undefined||v==="")return "—";return typeof v==="object"?JSON.stringify(v):String(v);}
function firebaseError(error:unknown){const code=typeof error==="object"&&error&&"code"in error?String((error as {code?:unknown}).code):"";return ({"auth/invalid-credential":"The email or password is incorrect.","auth/email-already-in-use":"An account already exists for this email.","auth/weak-password":"Choose a stronger password.","auth/invalid-email":"Enter a valid email address.","auth/too-many-requests":"Too many attempts. Please wait and try again."} as Record<string,string>)[code]??(error instanceof Error?error.message:"Authentication failed.");}
function apiError(error:unknown){if(error instanceof ApiError)return error.status===401?"Your authenticated session is no longer valid. Please sign in again.":error.status===403?error.message:error.message;return error instanceof Error?error.message:"Unable to reach the authoritative API.";}
function Field({label,children,help}:{label:string;children:React.ReactNode;help?:string}){return <label className="form-field"><span>{label}</span>{children}{help&&<small>{help}</small>}</label>}

function App(){
 const [mode,setMode]=useState<"signin"|"register">("signin");
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [displayName,setDisplayName]=useState("");
 const [organizationName,setOrganizationName]=useState("");const [roleKey,setRoleKey]=useState("citizen");const [geographyId,setGeographyId]=useState("");
 const [geographyRoots,setGeographyRoots]=useState<Array<{id:string;name:string;kind:string}>>([]);
 const [token,setToken]=useState("");const [me,setMe]=useState<Me|null>(null);const [healthState,setHealthState]=useState<Health|null>(null);const [overview,setOverview]=useState<{counts:Record<string,number>}|null>(null);const [sources,setSources]=useState<RegulatorySource[]|null>(null);
 const [workspaceData,setWorkspaceData]=useState<Partial<Record<WorkspaceKey,Workspace>>>({});const [workspaceErrors,setWorkspaceErrors]=useState<Partial<Record<WorkspaceKey,string>>>({});const [workspaceLoading,setWorkspaceLoading]=useState<Partial<Record<WorkspaceKey,boolean>>>({});const [selectedWorkspace,setSelectedWorkspace]=useState<WorkspaceKey>("mrv");
 const [reviewQueue,setReviewQueue]=useState<ReviewApplication[]>([]);const [reviewForbidden,setReviewForbidden]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 const membership=me?.memberships[0];const pending=me?.applications.find(a=>a.status==="PENDING");const selected=workspaces.find(w=>w.key===selectedWorkspace)!;const selectedData=workspaceData[selectedWorkspace];const rows=selectedData?((selectedData[selected.collection]??selectedData.data?.[selected.collection]??[]) as unknown[]):[];const total=useMemo(()=>overview?Object.values(overview.counts).reduce((a,b)=>a+b,0):0,[overview]);
 const [deviceId,setDeviceId]=useState("");const [activityType,setActivityType]=useState("WASTE_COLLECTION");const [activityId,setActivityId]=useState("");const [measurementId,setMeasurementId]=useState("");const [evidenceId,setEvidenceId]=useState("");const [credentialId,setCredentialId]=useState("");const [verificationId,setVerificationId]=useState("");const [trustRootId,setTrustRootId]=useState("");const [targetOrganizationId,setTargetOrganizationId]=useState("");const [payerId,setPayerId]=useState("");const [payeeId,setPayeeId]=useState("");const [amount,setAmount]=useState("");const [currency,setCurrency]=useState("INR");const [actionBusy,setActionBusy]=useState(false);

 useEffect(()=>{void health().then(setHealthState).catch(()=>setHealthState(null));void api<{stakeholders:Array<{key:string;label:string}>}>("/api/v1/onboarding/options").catch(()=>undefined);},[]);
 async function loadWorkspace(key:WorkspaceKey,session=token){if(!session)return;const w=workspaces.find(x=>x.key===key)!;setWorkspaceLoading(p=>({...p,[key]:true}));setWorkspaceErrors(p=>({...p,[key]:undefined}));try{const data=await api<Workspace>(w.path,session);setWorkspaceData(p=>({...p,[key]:data}));}catch(cause){setWorkspaceErrors(p=>({...p,[key]:apiError(cause)}));}finally{setWorkspaceLoading(p=>({...p,[key]:false}));}}
 async function loadReviewQueue(session:string){try{const result=await api<{applications:ReviewApplication[]}>("/api/v1/onboarding/review-queue",session);setReviewQueue(result.applications);setReviewForbidden(false);}catch(cause){if(cause instanceof ApiError&&cause.status===403)setReviewForbidden(true);else setReviewForbidden(false);setReviewQueue([]);}}
 async function loadSession(session:string){setBusy(true);setError("");try{const identity=await api<Me>("/api/v1/auth/me",session);setMe(identity);const reg=await api<{sources:RegulatorySource[]}>("/api/v1/regulatory/sources");setSources(reg.sources);if(identity.memberships.length){const o=await api<{counts:Record<string,number>}>("/api/v1/overview",session);setOverview(o);await Promise.all(workspaces.map(w=>loadWorkspace(w.key,session)));await loadReviewQueue(session);}else{setOverview(null);setWorkspaceData({});setWorkspaceErrors({});setReviewQueue([]);await api<{data:{geography:Array<{id:string;name:string;kind:string}>}}>("/api/v1/geography/roots",session).then(r=>setGeographyRoots(r.data.geography)).catch(()=>setGeographyRoots([]));}}catch(cause){setToken("");setMe(null);setOverview(null);setWorkspaceData({});setError(apiError(cause));}finally{setBusy(false);}}
 async function establishSession(idToken:string){const response=await api<{sessionToken:string}>("/api/v1/auth/exchange","",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken})});setToken(response.sessionToken);await loadSession(response.sessionToken);}
 async function authenticateUser(){if(!firebaseAuth){setError("Authentication is not configured for this deployment. Configure the VITE_FIREBASE_* variables.");return;}if(!email.trim()||!password){setError("Email and password are required.");return;}setBusy(true);setError("");setMessage("");try{const credential=mode==="register"?await createUserWithEmailAndPassword(firebaseAuth,email.trim(),password):await signInWithEmailAndPassword(firebaseAuth,email.trim(),password);if(mode==="register"){if(displayName.trim())await updateProfile(credential.user,{displayName:displayName.trim()});await sendEmailVerification(credential.user);await signOut(firebaseAuth);setMode("signin");setMessage("Account created. Verify your email, then sign in to continue stakeholder onboarding.");return;}if(!credential.user.emailVerified){await signOut(firebaseAuth);setError("Verify your email address before accessing RupayKG.");return;}await establishSession(await credential.user.getIdToken(true));}catch(cause){setError(cause instanceof ApiError?cause.message:firebaseError(cause));}finally{setBusy(false);}}
 async function submitApplication(){if(!token||!organizationName.trim())return;setBusy(true);setError("");setMessage("");try{const result=await api<{message:string}>("/api/v1/onboarding/applications",token,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationName:organizationName.trim(),roleKey,geographyId:geographyId||undefined,applicantNote:"Stakeholder self-service onboarding"})});setMessage(result.message);await loadSession(token);}catch(cause){setError(apiError(cause));}finally{setBusy(false);}}
 async function approveApplication(id:string){setActionBusy(true);setError("");try{await api(`/api/v1/onboarding/applications/${id}/approve`,token,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});setMessage("Stakeholder application approved and membership verified.");await loadReviewQueue(token);await loadSession(token);}catch(cause){setError(apiError(cause));}finally{setActionBusy(false);}}
 async function logout(){if(token)await fetch("/api/v1/auth/logout",{method:"POST",headers:{Authorization:`Bearer ${token}`}}).catch(()=>undefined);if(firebaseAuth)await signOut(firebaseAuth).catch(()=>undefined);setToken("");setMe(null);setOverview(null);setWorkspaceData({});setReviewQueue([]);setMessage("You have been signed out.");setError("");}
 async function runOperation(operationType:string,payload:Record<string,unknown>){if(!token||!deviceId.trim()){setError("A verified field-device ID is required for field operation intake.");return;}setActionBusy(true);setError("");setMessage("");try{const body={idempotencyKey:crypto.randomUUID(),deviceId:deviceId.trim(),capturedAt:new Date().toISOString(),payload:{operationType,...payload}};const result=await api<{operation?:unknown}>("/api/v1/operations/sync",token,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage(`Authoritative operation accepted: ${value(result.operation)}`);await refreshData();}catch(cause){setError(apiError(cause));}finally{setActionBusy(false);}}
 async function mutate(path:string,body:Record<string,unknown>){setActionBusy(true);setError("");setMessage("");try{const result=await api<unknown>(path,token,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage(`Authoritative mutation completed: ${value(result)}`);await refreshData();}catch(cause){setError(apiError(cause));}finally{setActionBusy(false);}}
 async function refreshData(){if(!token)return;const o=await api<{counts:Record<string,number>}>("/api/v1/overview",token).catch(()=>null);if(o)setOverview(o);await loadWorkspace(selectedWorkspace,token);}
 async function logoutAndClear(){await logout();}

 return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">R</span><div><strong>RupayKG</strong><span>circular economy operating system</span></div></div><div className="system-state" aria-live="polite"><span className={`dot ${healthState?.status==="READY"?"ready":""}`}/>{healthState?.status==="READY"?"Backend ready":healthState?.status==="DEGRADED"?"Backend degraded":"Backend status unavailable"}</div></header><main>
 <section className="hero"><div><p className="eyebrow">STAKEHOLDER OPERATING SYSTEM</p><h1>From physical activity to verified value.</h1><p className="lede">The UI is a control surface for the authoritative backend: authentication, organization membership, permissions, geography scope and workflow state are enforced server-side.</p></div><div className="authority-card"><span>Source of truth</span><strong>PostgreSQL</strong><small>{healthState?.status==="READY"?"Authoritative database available":"Authoritative database unavailable"}</small></div></section>
 {!token?<section className="auth-card"><div className="auth-copy"><p className="eyebrow">{mode==="register"?"CREATE STAKEHOLDER ACCOUNT":"STAKEHOLDER LOGIN"}</p><h2>{mode==="register"?"Join the operating network":"Sign in to your stakeholder workspace"}</h2><p>Firebase handles authentication. RupayKG exchanges a verified Firebase identity for a revocable application session.</p></div><form className="auth-form" onSubmit={e=>{e.preventDefault();void authenticateUser()}}>{mode==="register"&&<><input aria-label="Full name" value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Full name" autoComplete="name"/><p className="field-help">You must verify your email before signing in.</p></>}<input aria-label="Email address" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" autoComplete="email" required/><input aria-label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" autoComplete={mode==="register"?"new-password":"current-password"} required/><button type="submit" disabled={busy||!firebaseConfigured}>{busy?"Authenticating…":mode==="register"?"Create account":"Sign in"}</button>{!firebaseConfigured&&<p className="field-help">Firebase client configuration is missing.</p>}<button type="button" className="secondary auth-switch" onClick={()=>{setMode(mode==="register"?"signin":"register");setError("");setMessage("")}}>{mode==="register"?"Already have an account? Sign in":"New stakeholder? Create an account"}</button></form></section>:<section className="identity-bar"><div><p className="eyebrow">AUTHENTICATED STAKEHOLDER</p><strong>{me?.identity?.display_name??"Stakeholder"}</strong><span>{membership?`${roleLabels[membership.role_name]??membership.role_name} · ${membership.organization_name}`:"No verified organization membership yet"}</span></div><div className="identity-actions"><button type="button" className="secondary" onClick={()=>void loadSession(token)} disabled={busy}>Refresh</button><button type="button" className="secondary" onClick={()=>void logoutAndClear()}>Sign out</button></div></section>}
 {error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice success" role="status">{message}</div>}
 {token&&!membership&&<section className="onboarding-card"><div><p className="eyebrow">STAKEHOLDER ONBOARDING</p><h2>{pending?"Application under review":"Tell RupayKG how you participate"}</h2><p>{pending?"Your identity is authenticated, but operational access remains blocked until a verified platform authority approves the organization membership.":"Choose the real-world stakeholder relationship. Submission creates a pending membership and never grants permissions directly."}</p></div>{!pending&&<div className="onboarding-form"><Field label="Stakeholder role"><select value={roleKey} onChange={e=>setRoleKey(e.target.value)}>{Object.entries(roleLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="Organization / operating name"><input value={organizationName} onChange={e=>setOrganizationName(e.target.value)} placeholder="Organization, household, farm, facility or operating unit"/></Field><Field label="Geography scope (optional)"><select value={geographyId} onChange={e=>setGeographyId(e.target.value)}><option value="">No geography supplied</option>{geographyRoots.map(g=><option key={g.id} value={g.id}>{g.name} · {g.kind}</option>)}</select></Field><button type="button" onClick={()=>void submitApplication()} disabled={busy||!organizationName.trim()}>Submit stakeholder application</button></div>}</section>}
 {token&&membership&&<>
 <section className="section-heading"><div><p className="eyebrow">{roleLabels[membership.role_name]??membership.role_name}</p><h2>{membership.organization_name}</h2></div><span>{total} recorded items</span></section>
 <section className="metrics">{Object.entries(labels).map(([key,label])=><article className="metric" key={key}><span>{label}</span><strong>{overview?.counts[key]??"—"}</strong><small>{overview?"Authoritative PostgreSQL":"Loading"}</small></article>)}</section>
 {reviewQueue.length>0&&!reviewForbidden&&<section className="review-panel"><div className="section-heading"><div><p className="eyebrow">GOVERNANCE</p><h2>Stakeholder verification queue</h2></div><span>{reviewQueue.length} pending</span></div>{reviewQueue.map(app=><article className="review-row" key={app.id}><div><strong>{app.applicant_name}</strong><span>{roleLabels[app.requested_role_key]??app.requested_role_key} · {app.organization_name}</span><small>{app.applicant_email??"No email"} · submitted {new Date(app.created_at).toLocaleString()}</small>{app.applicant_note&&<small>{app.applicant_note}</small>}</div><button type="button" onClick={()=>void approveApplication(app.id)} disabled={actionBusy}>Approve</button></article>)}</section>}
 <section className="section-heading"><div><p className="eyebrow">OPERATING WORKSPACES</p><h2>Authoritative backend projections</h2></div><span>Read scope is server-enforced</span></section>
 <nav className="workspace-tabs" aria-label="Operating workspaces">{workspaces.map(w=><button type="button" key={w.key} className={selectedWorkspace===w.key?"tab active":"tab"} onClick={()=>{setSelectedWorkspace(w.key);void loadWorkspace(w.key)}} aria-pressed={selectedWorkspace===w.key}>{w.label}</button>)}</nav>
 <section className="workspace-panel"><div className="workspace-panel-head"><div><strong>{selected.label}</strong><span>{workspaceLoading[selectedWorkspace]?"Loading authoritative records…":workspaceErrors[selectedWorkspace]??`${rows.length} records returned`}</span></div><button type="button" className="secondary" onClick={()=>void loadWorkspace(selectedWorkspace)} disabled={workspaceLoading[selectedWorkspace]}>Refresh</button></div>{rows.length?rows.slice(0,100).map((row,index)=><article className="workspace-row" key={index}><div className="workspace-title"><strong>{value((row as Record<string,unknown>).title??(row as Record<string,unknown>).activity_type??(row as Record<string,unknown>).status??selected.label)}</strong><span>{selected.label}</span></div><div className="workspace-fields">{Object.entries((row&&typeof row==="object"?row:{value:row}) as Record<string,unknown>).filter(([key])=>!['metadata','inputs','result','calculation_trace'].includes(key)).slice(0,7).map(([key,field])=><span key={key}><b>{key.replaceAll("_"," ")}</b>{value(field)}</span>)}</div></article>):<div className="empty">{workspaceErrors[selectedWorkspace]??"The authoritative API returned no records for this workspace."}</div>}</section>
 <section className="operation-console"><div className="section-heading"><div><p className="eyebrow">AUTHORITATIVE MUTATIONS</p><h2>Operate through the real API</h2></div><span>No UI-only state changes</span></div>
 <div className="operation-grid"><article><h3>Field MRV intake</h3><p>Offline-style operation intake requires a verified enrolled device and current server permissions.</p><Field label="Verified device ID"><input value={deviceId} onChange={e=>setDeviceId(e.target.value)} placeholder="Field device UUID"/></Field><Field label="Activity type"><input value={activityType} onChange={e=>setActivityType(e.target.value)} /></Field><Field label="Activity ID (for measurement/evidence)"><input value={activityId} onChange={e=>setActivityId(e.target.value)} placeholder="Existing activity UUID"/></Field><div className="button-row"><button type="button" onClick={()=>void runOperation("ACTIVITY_CREATE",{organizationId:membership.organization_id,activityType,geographyId:geographyId||undefined,occurredAt:new Date().toISOString()})} disabled={actionBusy||!deviceId}>Create activity</button><button type="button" className="secondary" onClick={()=>void runOperation("MEASUREMENT_CREATE",{activityId,value:1,unit:"kg",method:"FIELD",source:"FIELD_DEVICE",measuredAt:new Date().toISOString()})} disabled={actionBusy||!deviceId||!activityId}>Create measurement</button><button type="button" className="secondary" onClick={()=>void runOperation("EVIDENCE_CREATE",{activityId,evidenceType:"FIELD_RECORD",capturedAt:new Date().toISOString(),contentHash:"ui-placeholder-requires-real-content-hash"})} disabled={actionBusy||!deviceId||!activityId}>Create evidence</button></div></article>
 <article><h3>Carbon calculation</h3><p>Calculation is blocked until activity geography, verified evidence and approved verification are present.</p><Field label="Activity ID"><input value={activityId} onChange={e=>setActivityId(e.target.value)}/></Field><Field label="Evidence ID"><input value={evidenceId} onChange={e=>setEvidenceId(e.target.value)}/></Field><Field label="Methodology code"><input id="methodology-code" placeholder="Registered methodology code"/></Field><Field label="Methodology version"><input id="methodology-version" placeholder="Registered version"/></Field><div className="button-row"><button type="button" onClick={()=>{const code=(document.getElementById("methodology-code") as HTMLInputElement)?.value;const version=(document.getElementById("methodology-version") as HTMLInputElement)?.value;void mutate("/api/v1/carbon/calculations",{activityId,methodologyCode:code,methodologyVersion:version,evidenceId,baselineTco2e:1,projectTco2e:0,leakageTco2e:0,uncertaintyTco2e:0})}} disabled={actionBusy||!activityId||!evidenceId}>Calculate value</button></div></article>
 <article><h3>Credential registry</h3><p>High-risk registry transitions remain permission- and state-gated by the backend.</p><Field label="Credential ID"><input value={credentialId} onChange={e=>setCredentialId(e.target.value)} placeholder="Credential UUID"/></Field><Field label="Verification ID (issuance)"><input value={verificationId} onChange={e=>setVerificationId(e.target.value)} placeholder="Approved verification UUID"/></Field><Field label="Trust root ID (issuance)"><input value={trustRootId} onChange={e=>setTrustRootId(e.target.value)} placeholder="Trust root UUID"/></Field><Field label="Transfer destination organization ID"><input value={targetOrganizationId} onChange={e=>setTargetOrganizationId(e.target.value)} placeholder="Organization UUID"/></Field><div className="button-row"><button type="button" onClick={()=>void mutate("/api/v1/credentials",{activityId,trustRootId,verificationId,issuerOrganizationId:membership.organization_id,quantity:1,unit:"tCO2e"})} disabled={actionBusy||!activityId||!verificationId||!trustRootId}>Issue</button><button type="button" className="secondary" onClick={()=>void mutate(`/api/v1/credentials/${credentialId}/activate`,{})} disabled={actionBusy||!credentialId}>Activate</button><button type="button" className="secondary" onClick={()=>void mutate(`/api/v1/credentials/${credentialId}/transfer`,{toOwnerId:targetOrganizationId})} disabled={actionBusy||!credentialId||!targetOrganizationId}>Transfer</button><button type="button" className="secondary" onClick={()=>void mutate(`/api/v1/credentials/${credentialId}/retire`,{})} disabled={actionBusy||!credentialId}>Retire</button></div></article>
 <article><h3>Settlement</h3><p>Settlement creation is allowed only when the credential has an authoritative registry state and the current owner constraints pass.</p><Field label="Credential ID"><input value={credentialId} onChange={e=>setCredentialId(e.target.value)}/></Field><Field label="Payer organization ID"><input value={payerId} onChange={e=>setPayerId(e.target.value||membership.organization_id)}/></Field><Field label="Payee organization ID"><input value={payeeId} onChange={e=>setPayeeId(e.target.value)}/></Field><div className="button-row"><input aria-label="Settlement amount" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount"/><input aria-label="Currency" maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/><button type="button" onClick={()=>void mutate("/api/v1/settlements",{credentialId,payerId:payerId||membership.organization_id,payeeId,amount:Number(amount),currency})} disabled={actionBusy||!credentialId||!payeeId||!amount}>Create settlement</button></div></article></div></section>
 </>}
 <section className="section-heading"><div><p className="eyebrow">REGULATORY PROVENANCE</p><h2>Source catalogue</h2></div><span>{sources?`${sources.length} authoritative records`:"Loading…"}</span></section><section className="source-list">{sources?.length?sources.map(source=><article className="source-row" key={source.id}><div><strong>{source.title}</strong><p>{source.authority} · {source.instrument} · {source.reference}</p></div><span className="status-pill">{source.status}</span></article>):<div className="empty">No regulatory records are available from the authoritative database.</div>}</section>
 </main><footer><span>RupayKG</span><span>Backend-authoritative · UI never grants access or fabricates production state</span></footer></div>;
}
createRoot(document.getElementById("root")!).render(<App/>);
