import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { createUserWithEmailAndPassword, getAuth, sendEmailVerification, setPersistence, signInWithEmailAndPassword, signOut, browserSessionPersistence, updateProfile } from "firebase/auth";
import { initializeApp } from "firebase/app";
import "./styles.css";

type Health={status:"READY"|"DEGRADED";database:"AVAILABLE"|"UNAVAILABLE";syntheticData:boolean};
type Membership={organization_id:string;role_id:string;status:string;role_name:string;organization_name:string;organization_type:string;permissions:string[];can_assess_epr?:boolean;can_write_esg?:boolean};
type Application={id:string;organization_id:string;requested_role_key:string;requested_organization_type:string;geography_id?:string|null;status:string;created_at:string};
type Me={identity:{id:string;display_name:string;email?:string|null;status:string}|null;memberships:Membership[];applications:Application[]};
type Workspace={source:string;syntheticData:boolean;data?:Record<string,unknown>;[key:string]:unknown};
type WorkspaceKey="resource-flows"|"mrv"|"compliance"|"carbon"|"registry"|"settlement"|"esg"|"intelligence";
type WorkspaceDef={key:WorkspaceKey;label:string;path:string;collection:string;description:string};
const firebaseConfig={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const firebaseConfigured=Object.values(firebaseConfig).every(Boolean);const firebaseAuth=firebaseConfigured?getAuth(initializeApp(firebaseConfig)):null;if(firebaseAuth)void setPersistence(firebaseAuth,browserSessionPersistence);
const roles:Record<string,string>={citizen:"Citizen / household",farmer:"Farmer / rural producer",safai_mitra:"Waste collection worker",fpo:"FPO / rural enterprise",municipal_admin:"ULB / municipal authority",municipal_generator:"Municipal / bulk generator",aggregator:"Collector / aggregator / transporter",processor:"MRF / recycler / processor",industry_generator:"Industrial generator",commercial_generator:"Commercial generator",institution_generator:"Institutional generator",PROJECT_OWNER:"Carbon project owner",ACVA_USER:"MRV / assurance user",ccc_buyer:"Carbon / ESG buyer",epr_partner:"EPR partner",csr_partner:"CSR / ESG partner",regulator:"Regulator / public authority"};
const workspaces:WorkspaceDef[]=[
 {key:"resource-flows",label:"Operations",path:"/api/v1/workspaces/resource-flows",collection:"resourceFlows",description:"Generation, collection, transport and processing resource flows."},
 {key:"mrv",label:"MRV & Evidence",path:"/api/v1/workspaces/mrv",collection:"activities",description:"Measurement, evidence, provenance and verification."},
 {key:"compliance",label:"Compliance & EPR",path:"/api/v1/workspaces/compliance",collection:"obligations",description:"Applicability, obligations and evidence-backed compliance."},
 {key:"carbon",label:"Carbon & Value",path:"/api/v1/workspaces/carbon",collection:"calculations",description:"Methodology, calculation and value eligibility."},
 {key:"registry",label:"Registry",path:"/api/v1/workspaces/registry",collection:"credentials",description:"Credential issuance, ownership, transfer and retirement."},
 {key:"settlement",label:"Settlement",path:"/api/v1/workspaces/settlement",collection:"settlements",description:"Authorization, execution, reconciliation and settlement."},
 {key:"esg",label:"ESG / BRSR",path:"/api/v1/workspaces/esg",collection:"reports",description:"Traceable ESG and regulatory reporting outputs."},
 {key:"intelligence",label:"Intelligence",path:"/api/v1/workspaces/intelligence",collection:"findings",description:"Findings, risks and recommended actions."}
];
const lifecycle=[
 ["GENERATION","Physical activity captured"],["AGGREGATION","Collection / consolidation"],["MEASUREMENT","Quantity and method recorded"],["TRANSPORT","Movement evidence"],["PROCESSING","Intake and processing"],["EVIDENCE","Authoritative evidence"],["VERIFICATION","Independent verification"],["VALUE_ELIGIBLE","Verified value may proceed"],["CERTIFIED","Credential / certification"],["REGISTERED","Registry state"],["TRANSFERRED","Transfer / retirement"],["SETTLED","Reconciled settlement"],["REPORTED","ESG / regulatory reporting"]
] as const;
class ApiError extends Error{status:number;constructor(message:string,status:number){super(message);this.status=status;}}
async function api<T>(path:string,token="",init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set("Accept","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);const r=await fetch(path,{...init,headers});const b=await r.json().catch(()=>({}));if(!r.ok)throw new ApiError(b?.error??`Request failed (${r.status})`,r.status);return b as T;}
function display(v:unknown){if(v===null||v===undefined||v==="")return "—";return typeof v==="object"?JSON.stringify(v):String(v)}
function App(){
 const [mode,setMode]=useState<"signin"|"register">("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[token,setToken]=useState(""),[me,setMe]=useState<Me|null>(null),[orgId,setOrgId]=useState(""),[healthState,setHealthState]=useState<Health|null>(null),[overview,setOverview]=useState<{counts:Record<string,number>}|null>(null),[data,setData]=useState<Partial<Record<WorkspaceKey,Workspace>>>({}),[loading,setLoading]=useState(false),[selected,setSelected]=useState<WorkspaceKey>("resource-flows"),[error,setError]=useState(""),[message,setMessage]=useState("");
 const verified=useMemo(()=>me?.memberships.filter(m=>m.status==="VERIFIED")??[],[me]);const membership=verified.find(m=>m.organization_id===orgId)??verified[0];const pending=me?.applications.find(a=>a.status==="PENDING");
 const permission=(...p:string[])=>p.some(x=>membership?.permissions.includes(x));
 const role=membership?roles[membership.role_name]??membership.role_name:"Unassigned";
 const counts=overview?.counts??{};
 const stages=useMemo(()=>{const a=Number(counts.activities||0),m=Number(counts.measurements||0),e=Number(counts.evidence||0),v=Number(counts.approvedVerifications||0),c=Number(counts.issuedOrActiveCredentials||0),s=Number(counts.settledTransactions||0);return lifecycle.map(([key,label],i)=>({key,label,done:i===0?a>0:i===1?m>0:i===2?m>0:i===3?m>0:i===4?m>0:i===5?e>0:i===6?v>0:i===7?v>0:i===8?c>0:i===9?c>0:i===10?c>0:i===11?s>0:i===12?s>0:false}));},[counts]);
 async function loadWorkspace(key:WorkspaceKey,t=token){if(!t)return;const w=workspaces.find(x=>x.key===key)!;try{const result=await api<Workspace>(w.path,t);setData(p=>({...p,[key]:result}));}catch(e){setError(e instanceof Error?e.message:"Unable to load authoritative workspace");}}
 async function refresh(t=token){if(!t)return;setLoading(true);setError("");try{const o=await api<{counts:Record<string,number>}>("/api/v1/overview",t);setOverview(o);await Promise.all(workspaces.map(w=>loadWorkspace(w.key,t)));}catch(e){setError(e instanceof Error?e.message:"Unable to load authoritative data");}finally{setLoading(false);}}
 async function session(t:string){setLoading(true);setError("");try{const identity=await api<Me>("/api/v1/auth/me",t);setMe(identity);const first=identity.memberships.find(m=>m.status==="VERIFIED");if(first)setOrgId(first.organization_id);if(first){await refresh(t);} }catch(e){setError(e instanceof Error?e.message:"Session could not be established");}finally{setLoading(false);}}
 async function auth(){if(!firebaseAuth){setError("Firebase authentication is not configured.");return}if(!email||!password){setError("Email and password are required.");return}setLoading(true);setError("");try{const c=mode==="register"?await createUserWithEmailAndPassword(firebaseAuth,email.trim(),password):await signInWithEmailAndPassword(firebaseAuth,email.trim(),password);if(mode==="register"){if(name.trim())await updateProfile(c.user,{displayName:name.trim()});await sendEmailVerification(c.user);await signOut(firebaseAuth);setMode("signin");setMessage("Account created. Verify your email before signing in.");return}if(!c.user.emailVerified){await signOut(firebaseAuth);setError("Verify your email address before accessing RupayKG.");return}const exchanged=await api<{sessionToken:string}>("/api/v1/auth/exchange","",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken:await c.user.getIdToken(true)})});setToken(exchanged.sessionToken);await session(exchanged.sessionToken);}catch(e){setError(e instanceof ApiError?e.message:e instanceof Error?e.message:"Authentication failed");}finally{setLoading(false)}}
 async function logout(){if(token)await fetch("/api/v1/auth/logout",{method:"POST",headers:{Authorization:`Bearer ${token}`}}).catch(()=>undefined);if(firebaseAuth)await signOut(firebaseAuth).catch(()=>undefined);setToken("");setMe(null);setOverview(null);setData({});setOrgId("");}
 useEffect(()=>{fetch("/health",{headers:{Accept:"application/json"}}).then(r=>r.json()).then(setHealthState).catch(()=>setHealthState(null));},[]);
 useEffect(()=>{if(token&&membership?.organization_id&&membership.organization_id!==orgId)setOrgId(membership.organization_id)},[token,membership?.organization_id,orgId]);
 const current=workspaces.find(w=>w.key===selected)!;const rows=(data[selected]?.[current.collection]??data[selected]?.data?.[current.collection]??[]) as unknown[];
 return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">R</span><div><strong>RupayKG</strong><span>circular economy operating system</span></div></div><div className="system-state"><span className={`dot ${healthState?.status==="READY"?"ready":""}`}/>{healthState?.status==="READY"?"Backend ready":"Backend status unavailable"}</div></header><main>
 {!token?<section className="auth-card"><div className="auth-copy"><p className="eyebrow">STAKEHOLDER OPERATING SYSTEM</p><h1>From physical activity to verified value.</h1><p>Sign in to an authoritative, organization-scoped operating environment for waste, MRV, EPR, carbon, registry, settlement and ESG reporting.</p></div><form className="auth-form" onSubmit={e=>{e.preventDefault();void auth()}}>{mode==="register"&&<input aria-label="Full name" value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/>}<input aria-label="Email address" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" required/><input aria-label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/><button disabled={loading||!firebaseConfigured}>{loading?"Working…":mode==="register"?"Create account":"Sign in"}</button><button type="button" className="secondary" onClick={()=>setMode(mode==="register"?"signin":"register")}>{mode==="register"?"Sign in instead":"Create stakeholder account"}</button></form></section>:!membership?<section className="onboarding-card"><p className="eyebrow">STAKEHOLDER ONBOARDING</p><h2>{pending?"Application under review":"Organization membership required"}</h2><p>{pending?"Your identity is authenticated, but operational access remains blocked until platform approval.":"Complete the authoritative stakeholder onboarding process before accessing operational data."}</p><button className="secondary" onClick={()=>void session(token)}>Refresh status</button></section>:<>
 <section className="identity-bar"><div><p className="eyebrow">ACTIVE STAKEHOLDER CONTEXT</p><strong>{membership.organization_name}</strong><span>{role} · {membership.organization_type}</span></div><div className="identity-actions">{verified.length>1&&<label className="form-field"><span>Organization</span><select value={membership.organization_id} onChange={e=>{setOrgId(e.target.value);localStorage.setItem("rupaykg.activeOrganizationId",e.target.value);void refresh(token)}}>{verified.map(m=><option key={m.organization_id} value={m.organization_id}>{m.organization_name} · {roles[m.role_name]??m.role_name}</option>)}</select></label>}<button className="secondary" onClick={()=>void refresh()} disabled={loading}>Refresh</button><button className="secondary" onClick={()=>void logout()}>Sign out</button></div></section>
 <section className="hero lifecycle-hero"><div><p className="eyebrow">AUTHORITATIVE LIFECYCLE</p><h1>Operate the journey, not isolated workspaces.</h1><p className="lede">Every downstream value depends on upstream records, evidence, verification and authority-backed state. The UI exposes that dependency directly.</p></div><div className="authority-card"><span>Current organization</span><strong>{membership.organization_name}</strong><small>{role}</small></div></section>
 <section className="lifecycle-strip" aria-label="RupayKG lifecycle">{stages.map((s,i)=><div key={s.key} className={`lifecycle-stage ${s.done?"done":""}`}><span>{i+1}</span><strong>{s.key.replaceAll("_"," ")}</strong><small>{s.label}</small></div>)}</section>
 <section className="metrics">{[["Activities",counts.activities],["Measurements",counts.measurements],["Evidence",counts.evidence],["Verified",counts.approvedVerifications],["Open obligations",counts.openObligations],["Credentials",counts.issuedOrActiveCredentials],["Settled",counts.settledTransactions]].map(([label,n])=><article className="metric" key={String(label)}><span>{label}</span><strong>{n??"—"}</strong><small>Authoritative backend</small></article>)}</section>
 <section className="section-heading"><div><p className="eyebrow">STAKEHOLDER COMMAND CENTRE</p><h2>{role}</h2></div><span>{membership.can_write_esg?"ESG reporting enabled":membership.can_assess_epr?"EPR assessment enabled":"Role permissions enforced server-side"}</span></section>
 <section className="command-grid">{stages.filter(s=>!s.done).slice(0,4).map(s=><article className="command-card" key={s.key}><span className="status-pill">ACTION</span><h3>{s.key.replaceAll("_"," ")}</h3><p>{s.label}. Complete the upstream authoritative requirement before proceeding.</p><button onClick={()=>{const target=s.key==="EVIDENCE"?"mrv":s.key==="VERIFICATION"?"mrv":s.key==="VALUE_ELIGIBLE"?"carbon":s.key==="CERTIFIED"||s.key==="REGISTERED"?"registry":s.key==="SETTLED"?"settlement":"resource-flows";setSelected(target as WorkspaceKey);void loadWorkspace(target as WorkspaceKey)}}>Open work area</button></article>)}{stages.every(s=>s.done)&&<article className="command-card"><span className="status-pill">CURRENT</span><h3>Lifecycle is fully progressed</h3><p>Use ESG / BRSR reporting and Intelligence to review traceability, exceptions and reporting readiness.</p><button onClick={()=>setSelected("esg")}>Open reporting</button></article>}</section>
 <section className="section-heading"><div><p className="eyebrow">WORK BY DOMAIN</p><h2>Authoritative workspaces</h2></div><span>Organization and permission scope are enforced by the API</span></section><nav className="workspace-tabs" aria-label="Authoritative workspaces">{workspaces.map(w=><button type="button" key={w.key} className={selected===w.key?"tab active":"tab"} onClick={()=>{setSelected(w.key);void loadWorkspace(w.key)}}>{w.label}</button>)}</nav>
 <section className="workspace-panel"><div className="workspace-panel-head"><div><strong>{current.label}</strong><span>{current.description}</span></div><button className="secondary" onClick={()=>void loadWorkspace(selected)} disabled={loading}>Refresh</button></div>{rows.length?rows.slice(0,100).map((row,i)=><article className="workspace-row" key={i}><div className="workspace-title"><strong>{display((row as Record<string,unknown>).title??(row as Record<string,unknown>).activity_type??(row as Record<string,unknown>).status??current.label)}</strong><span>{current.label}</span></div><div className="workspace-fields">{Object.entries(row&&typeof row==="object"?row:{value:row}).filter(([k])=>!['metadata','inputs','result','calculation_trace'].includes(k)).slice(0,7).map(([k,v])=><span key={k}><b>{k.replaceAll("_"," ")}</b>{display(v)}</span>)}</div></article>):<div className="empty">No records returned for this organization-scoped workspace.</div>}</section>
 <section className="provenance-card"><div><p className="eyebrow">CONTROL PRINCIPLE</p><h2>Evidence before value</h2><p>RupayKG does not let the UI invent verification, carbon eligibility, credentials, settlement confirmation or regulatory applicability. Those states remain authoritative backend decisions.</p></div><div className="provenance-list"><span>Organization scope</span><span>Geography scope</span><span>Measurement + evidence</span><span>Independent verification</span><span>Authority-backed registry</span><span>Reconciled settlement</span><span>Traceable ESG reporting</span></div></section>
 </>}
 {error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice success" role="status">{message}</div>}
 </main><footer><span>RupayKG</span><span>Backend-authoritative · lifecycle-driven UI · deployment remains a separate final gate</span></footer></div>;
}
createRoot(document.getElementById("root")!).render(<App/>);
