import { getApps, initializeApp } from "firebase/app";
import { getAuth, onAuthStateChanged, type User } from "firebase/auth";
import "./styles.css";

type Activity={id:string;activity_type:string;status:string;occurred_at:string};
type Verification={id:string;evidence_id:string;activity_id:string;decision:string;scope:string};
type Mrv={data:{activities?:Activity[];verifications?:Verification[]}};
const config={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const app=Object.values(config).every(Boolean)?(getApps().find(a=>a.name==="registry-issuance")??initializeApp(config,"registry-issuance")):null;
const auth=app?getAuth(app):null;const root=document.getElementById("registry-issuance");const orgKey="rupaykg.activeOrganizationId";
const esc=(v:unknown)=>String(v??"—").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]??c));
const api=async<T>(path:string,token:string,init:RequestInit={}):Promise<T>=>{const h=new Headers(init.headers);h.set("Accept","application/json");h.set("Authorization",`Bearer ${token}`);const org=localStorage.getItem(orgKey);if(org)h.set("X-RupayKG-Organization-Id",org);const r=await fetch(path,{...init,headers:h});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error??`Request failed (${r.status})`);return b as T};
let token="",activities:Activity[]=[],verifications:Verification[]=[],message="";
async function exchange(user:User){if(!user.emailVerified)throw new Error("Verified email is required before credential issuance.");const idToken=await user.getIdToken(true);const r=await fetch("/api/v1/auth/exchange",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error??"Authentication failed");token=String(b.sessionToken??"");if(!token)throw new Error("Authoritative session token was not returned.");}
async function load(user:User){await exchange(user);const m=await api<Mrv>("/api/v1/workspaces/mrv",token);activities=(m.data?.activities??[]).filter(a=>a.status==="COMPLETED");verifications=m.data?.verifications??[];render();}
function render(){if(!root)return;const options=activities.map(a=>`<option value="${esc(a.id)}">${esc(a.activity_type)} · ${esc(a.id)}</option>`).join("");root.innerHTML=`<section class="compliance-card"><div class="compliance-head"><div><p class="eyebrow">AUTHORITATIVE REGISTRY</p><h2>Credential issuance</h2><p>Issue a registry credential only from a completed activity with an approved verification. The backend remains the authority for permissions, evidence and lifecycle integrity.</p></div><span class="compliance-state">${esc(message||"AUTHORITATIVE")}</span></div><div class="compliance-list"><div class="compliance-row"><div style="width:100%"><strong>Issue credential</strong><div class="epr-return-form"><select id="issue-activity"><option value="">Select completed activity</option>${options}</select><select id="issue-verification"><option value="">Select approved verification</option></select><input id="issue-trust-root" placeholder="Trust root ID" autocomplete="off"><input id="issue-quantity" type="number" min="0.000001" step="0.000001" placeholder="Quantity"><input id="issue-unit" value="MT" aria-label="Credential unit"><button id="issue-submit">Issue credential</button></div><small class="field-help">Issuer organization: ${esc(localStorage.getItem(orgKey))}. High-risk ISSUE_CREDENTIAL authorization is enforced server-side.</small></div></div></div></section>`;
const activity=root.querySelector<HTMLSelectElement>("#issue-activity")!,verification=root.querySelector<HTMLSelectElement>("#issue-verification")!;activity.addEventListener("change",()=>{const id=activity.value;verification.innerHTML=`<option value="">Select approved verification</option>${verifications.filter(v=>v.activity_id===id&&v.decision==="APPROVED").map(v=>`<option value="${esc(v.id)}">${esc(v.id)} · ${esc(v.scope)}</option>`).join("")}`});root.querySelector<HTMLButtonElement>("#issue-submit")?.addEventListener("click",()=>void issue());}
async function issue(){try{const activityId=(root?.querySelector("#issue-activity") as HTMLSelectElement)?.value;const verificationId=(root?.querySelector("#issue-verification") as HTMLSelectElement)?.value;const trustRootId=(root?.querySelector("#issue-trust-root") as HTMLInputElement)?.value.trim();const quantity=Number((root?.querySelector("#issue-quantity") as HTMLInputElement)?.value);const unit=(root?.querySelector("#issue-unit") as HTMLInputElement)?.value.trim();const issuerOrganizationId=localStorage.getItem(orgKey)?.trim();if(!activityId||!verificationId||!trustRootId||!issuerOrganizationId||!Number.isFinite(quantity)||quantity<=0||!unit)throw new Error("Completed activity, approved verification, trust root, positive quantity and unit are required.");await api("/api/v1/credentials",token,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({activityId,trustRootId,verificationId,issuerOrganizationId,quantity,unit})});message="CREDENTIAL ISSUED";const user=auth?.currentUser;if(user)await load(user);}catch(e){message=e instanceof Error?e.message:"Credential issuance failed";render();}}
if(root){if(!auth)render();else onAuthStateChanged(auth,user=>{if(user)void load(user).catch(e=>{message=e instanceof Error?e.message:"Registry issuance unavailable";render();});else{message="SIGN IN REQUIRED";render();}});}
