import { getAuth, onAuthStateChanged, type User } from "firebase/auth";
import { initializeApp } from "firebase/app";
import "./styles.css";

type StatutoryProfile = { framework: string; rule_reference: string; applicability_status: string; determination_note?: string | null; externally_confirmed?: boolean; external_authority?: string | null; external_reference?: string | null };
type BwgAssessment = { id: string; assessment_date: string; floor_area_sq_m: number | null; water_consumption_lpd: number | null; solid_waste_kgpd: number | null; floor_area_threshold_sq_m: number; water_threshold_lpd: number; waste_threshold_kgpd: number; applicability_status: string; threshold_basis: string; evidence_id?: string | null; verification_id?: string | null; determination_note?: string | null };
type EprRecord = { id: string; scheme: string; rule_reference?: string | null; applicability_status: string; basis?: unknown; cpcb_registration_status: string; cpcb_registration_reference?: string | null; evidence_id?: string | null; verification_id?: string | null; determination_note?: string | null };
type Payload = { source: string; syntheticData: boolean; statutoryBoundary: string; profiles: StatutoryProfile[]; bwgAssessments: BwgAssessment[]; eprApplicability: EprRecord[] };
type Membership = { organization_id: string; status: string; permissions?: string[] };
type Exchange = { sessionToken: string; memberships?: Membership[] };
type Me = { memberships: Membership[] };

const firebaseConfig = { apiKey: import.meta.env.VITE_FIREBASE_API_KEY, authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN, projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID, appId: import.meta.env.VITE_FIREBASE_APP_ID };
const firebaseConfigured = Object.values(firebaseConfig).every(Boolean);
const firebaseAuth = firebaseConfigured ? getAuth(initializeApp(firebaseConfig, "statutory-applicability")) : null;
const root = document.getElementById("statutory-applicability");
const organizationKey = "rupaykg.activeOrganizationId";
const activeOrganizationId = () => window.localStorage.getItem(organizationKey)?.trim() ?? "";
const api = async <T,>(path: string, token = "", init: RequestInit = {}): Promise<T> => { const headers = new Headers(init.headers); headers.set("Accept", "application/json"); if (token) headers.set("Authorization", `Bearer ${token}`); const org = activeOrganizationId(); if (token && org) headers.set("X-RupayKG-Organization-Id", org); const response = await fetch(path, { ...init, headers }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error ?? `Request failed (${response.status})`); return body as T; };
const escapeHtml = (value: unknown) => String(value ?? "—").replace(/[&<>\"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c] ?? c));
const text = (value: unknown) => value === null || value === undefined || value === "" ? "—" : String(value);

if (root && firebaseAuth) {
  const render = (state: { status: string; message: string; data: Payload | null }) => {
    const data = state.data;
    const bwg = data?.bwgAssessments ?? [];
    const epr = data?.eprApplicability ?? [];
    const latest = bwg[0];
    root.innerHTML = `<section class="compliance-card statutory-card"><div class="compliance-head"><div><p class="eyebrow">STATUTORY APPLICABILITY</p><h2>SWM 2026 / EPR controls</h2><p>Organization-scoped applicability preparation using authoritative backend calculations. This panel does not issue CPCB registration, certificates, approvals or statutory determinations.</p></div><span class="compliance-state">${escapeHtml(state.status)}</span></div>${state.message ? `<div class="resource-flow-state">${escapeHtml(state.message)}</div>` : ""}<div class="compliance-list"><article class="compliance-row"><div><strong>Bulk Waste Generator assessment</strong><span>SWM Rules 2026 · S.O. 388(E) · effective 1 April 2026</span><small>Thresholds: ≥20,000 m² floor area OR ≥40,000 L/day water consumption OR ≥100 kg/day solid waste.</small>${latest ? `<small>Latest result: ${escapeHtml(latest.applicability_status)} · ${escapeHtml(latest.assessment_date)} · basis ${escapeHtml(latest.threshold_basis)}</small>` : `<small>No BWG assessment has been recorded for the active organization.</small>`}</div><div class="compliance-actions"><input id="bwg-floor" type="number" min="0" step="any" placeholder="Floor area m²"/><input id="bwg-water" type="number" min="0" step="any" placeholder="Water L/day"/><input id="bwg-waste" type="number" min="0" step="any" placeholder="Waste kg/day"/><input id="bwg-evidence" type="text" placeholder="Evidence ID (optional)"/><input id="bwg-verification" type="text" placeholder="Verification ID (optional)"/><button id="bwg-assess" type="button">Assess BWG applicability</button></div></article><article class="compliance-row"><div><strong>EPR applicability</strong><span>Prepare and track scheme applicability separately from external CPCB registration.</span><small>${epr.length ? epr.map(row => `${escapeHtml(row.scheme)} · ${escapeHtml(row.applicability_status)} · CPCB status ${escapeHtml(row.cpcb_registration_status)}`).join("<br/>") : "No EPR applicability record is available for the active organization."}</small></div><div class="compliance-actions"><input id="epr-scheme" type="text" placeholder="EPR scheme"/><select id="epr-status"><option value="UNDER_REVIEW">UNDER_REVIEW</option><option value="POTENTIALLY_APPLICABLE">POTENTIALLY_APPLICABLE</option><option value="APPLICABLE">APPLICABLE</option><option value="NOT_APPLICABLE">NOT_APPLICABLE</option><option value="UNKNOWN">UNKNOWN</option></select><input id="epr-note" type="text" placeholder="Determination note"/><input id="epr-evidence" type="text" placeholder="Evidence ID (optional)"/><input id="epr-verification" type="text" placeholder="Verification ID (optional)"/><button id="epr-save" type="button">Save EPR applicability</button></div></article></div><div class="field-help">External CPCB registration is represented only when an external registration reference exists. Internal preparation status is never presented as a CPCB-issued certificate or registration.</div></section>`;
    root.querySelector<HTMLButtonElement>("#bwg-assess")?.addEventListener("click", () => void assessBwg(state));
    root.querySelector<HTMLButtonElement>("#epr-save")?.addEventListener("click", () => void saveEpr(state));
  };
  const load = async (user: User) => {
    try { if (!user.emailVerified) throw new Error("Verify your email address before using statutory applicability."); const idToken = await user.getIdToken(true); const session = await api<Exchange>("/api/v1/auth/exchange", "", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idToken }) }); const verified = (session.memberships ?? []).filter(m => m.status === "VERIFIED"); if (!verified.length) throw new Error("A verified organization membership is required."); const selected = activeOrganizationId(); if (!verified.some(m => m.organization_id === selected)) window.localStorage.setItem(organizationKey, verified[0].organization_id); const me = await api<Me>("/api/v1/auth/me", session.sessionToken); if (!me.memberships.some(m => m.status === "VERIFIED" && m.organization_id === activeOrganizationId())) throw new Error("The active organization is not a verified membership."); const data = await api<Payload>("/api/v1/statutory/applicability", session.sessionToken); render({ status: "READY", message: "Applicability data loaded from PostgreSQL; no synthetic statutory values are generated.", data }); }
    catch (error) { render({ status: "UNAVAILABLE", message: error instanceof Error ? error.message : "Unable to load statutory applicability.", data: null }); }
  };
  const assessBwg = async (state: { status: string; message: string; data: Payload | null }) => {
    try { const user = firebaseAuth.currentUser; if (!user) throw new Error("Verified Firebase sign-in is required."); const session = await api<Exchange>("/api/v1/auth/exchange", "", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idToken: await user.getIdToken(true) }) }); const number = (id: string) => { const raw = root?.querySelector<HTMLInputElement>(id)?.value.trim() ?? ""; return raw === "" ? undefined : Number(raw); }; const body = { floorAreaSqM: number("#bwg-floor"), waterConsumptionLpd: number("#bwg-water"), solidWasteKgpd: number("#bwg-waste"), evidenceId: root?.querySelector<HTMLInputElement>("#bwg-evidence")?.value.trim() || undefined, verificationId: root?.querySelector<HTMLInputElement>("#bwg-verification")?.value.trim() || undefined }; const response = await api<{ assessment: BwgAssessment }>("/api/v1/statutory/bwg/assess", session.sessionToken, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); state.message = `BWG applicability recorded as ${response.assessment.applicability_status}.`; await load(user); }
    catch (error) { state.message = error instanceof Error ? error.message : "BWG assessment failed."; render(state); }
  };
  const saveEpr = async (state: { status: string; message: string; data: Payload | null }) => {
    try { const user = firebaseAuth.currentUser; if (!user) throw new Error("Verified Firebase sign-in is required."); const session = await api<Exchange>("/api/v1/auth/exchange", "", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idToken: await user.getIdToken(true) }) }); const value = (selector: string) => root?.querySelector<HTMLInputElement | HTMLSelectElement>(selector)?.value.trim() ?? ""; if (!value("#epr-scheme")) throw new Error("EPR scheme is required."); await api("/api/v1/statutory/epr", session.sessionToken, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scheme: value("#epr-scheme"), applicabilityStatus: value("#epr-status"), determinationNote: value("#epr-note") || undefined, evidenceId: value("#epr-evidence") || undefined, verificationId: value("#epr-verification") || undefined }) }); state.message = "EPR applicability preparation state recorded; external CPCB registration remains separate."; await load(user); }
    catch (error) { state.message = error instanceof Error ? error.message : "EPR applicability update failed."; render(state); }
  };
  onAuthStateChanged(firebaseAuth, user => { if (user) void load(user); else render({ status: "SIGN IN REQUIRED", message: "Sign in to load organization-scoped statutory applicability.", data: null }); });
  window.addEventListener("storage", event => { if (event.key === organizationKey) { const user = firebaseAuth.currentUser; if (user) void load(user); } });
}
