import { useEffect, useMemo, useState } from "react";
import { getAuth, onAuthStateChanged } from "firebase/auth";
import { getApps, initializeApp } from "firebase/app";
import "./ulb-command-center.css";

type Membership={organization_id:string;role_name:string;organization_name:string;organization_type:string;status:string;permissions:string[]};
type Me={memberships:Membership[]};
type Workspace={source?:string;syntheticData?:boolean;[key:string]:unknown};
type Counts=Record<string,number>;
type Row=Record<string,unknown>;
const cfg={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const firebaseConfigured=Object.values(cfg).every(Boolean);const app=firebaseConfigured?(getApps()[0]??initializeApp(cfg)):null;const auth=app?getAuth(app):null;
function orgId(){return localStorage.getItem("rupaykg.activeOrganizationId")??"";}
async function api<T>(path:string,token:string){const h=new Headers({Accept:"application/json",Authorization:`Bearer ${token}`});const id=orgId();if(id)h.set("x-rupaykg-organization-id",id);const r=await fetch(path,{headers:h});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json() as Promise<T>;}
const arr=(w:Workspace|undefined,key:string)=>((w?.[key]??(w?.data as Record<string,unknown>|undefined)?.[key]) as unknown[])??[];
const row=(v:unknown):Row=>v&&typeof v==="object"?v as Row:{};
const first=(r:Row,keys:string[])=>{for(const k of keys){const v=r[k];if(v!==null&&v!==undefined&&String(v).trim()!=="")return String(v)}return ""};
const statusOf=(r:Row)=>first(r,["status","decision","verification_status","state"]).toUpperCase()||"UNAVAILABLE";
const idOf=(r:Row)=>first(r,["id","activity_id","measurement_id","evidence_id","verification_id","flow_id"]);
const geoOf=(r:Row)=>first(r,["ward_name","ward","geography_name","geography_id","zone_name","zone","area_name","local_body_name"]);
const facilityOf=(r:Row)=>first(r,["facility_name","facility","site_name","site_id","plant_name","processing_facility","location_name"]);
function ULBCommandCenter(){
 const [token,setToken]=useState("");const [me,setMe]=useState<Me|null>(null);const [counts,setCounts]=useState<Counts>({});const [ops,setOps]=useState<Workspace>();const [mrv,setMrv]=useState<Workspace>();const [compliance,setCompliance]=useState<Workspace>();const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [geo,setGeo]=useState("ALL");const [facility,setFacility]=useState("ALL");
 useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,async user=>{if(!user||!user.emailVerified){setToken("");setMe(null);return}try{const ex=await api<{sessionToken:string}>("/api/v1/auth/exchange",await user.getIdToken(true));setToken(ex.sessionToken);setMe(await api<Me>("/api/v1/auth/me",ex.sessionToken));}catch{setToken("");setMe(null);}})},[]);
 const membership=useMemo(()=>{const id=orgId();return me?.memberships.find(m=>m.status==="VERIFIED"&&m.organization_id===id)??me?.memberships.find(m=>m.status==="VERIFIED");},[me]);
 const visible=!!membership&&(membership.role_name==="municipal_admin"||membership.role_name==="regulator"||membership.organization_type.toLowerCase().includes("municipal")||membership.organization_type.toLowerCase().includes("ulb"));
 async function refresh(){if(!token||!visible)return;setLoading(true);setError("");try{const [o,r,m,c]=await Promise.all([api<{counts:Counts}>("/api/v1/overview",token),api<Workspace>("/api/v1/workspaces/resource-flows",token),api<Workspace>("/api/v1/workspaces/mrv",token),api<Workspace>("/api/v1/workspaces/compliance",token)]);setCounts(o.counts??{});setOps(r);setMrv(m);setCompliance(c);}catch(e){setError(e instanceof Error?e.message:"Unable to load institutional data");}finally{setLoading(false)}}
 useEffect(()=>{if(visible)void refresh()},[visible,token]);
 if(!visible)return null;
 const flows=arr(ops,"resourceFlows").map(row),activities=arr(mrv,"activities").map(row),measurements=arr(mrv,"measurements").map(row),evidence=arr(mrv,"evidence").map(row),verifications=arr(mrv,"verifications").map(row),obligations=arr(compliance,"obligations").map(row);
 const verified=Number(counts.approvedVerifications??verifications.filter(x=>statusOf(x).includes("APPROV")).length);const open=Number(counts.openObligations??obligations.filter(x=>!statusOf(x).includes("CLOSED")).length);
 const sourceRows=flows.length?flows:activities;const geographies=Array.from(new Set(sourceRows.map(geoOf).filter(Boolean))).sort();const filteredFlows=flows.filter(x=>(geo==="ALL"||geoOf(x)===geo)&&(facility==="ALL"||facilityOf(x)===facility));const facilities=Array.from(new Set(filteredFlows.map(facilityOf).filter(Boolean))).sort();const selectedFlows=filteredFlows;const selectedIds=new Set(selectedFlows.flatMap(x=>[idOf(x),first(x,["activity_id"])].filter(Boolean)));
 const selectedMeasurements=measurements.filter(x=>!selectedIds.size||selectedIds.has(idOf(x))||selectedIds.has(first(x,["activity_id"])));const selectedEvidence=evidence.filter(x=>!selectedIds.size||selectedIds.has(idOf(x))||selectedIds.has(first(x,["activity_id"])));const selectedVerifications=verifications.filter(x=>!selectedIds.size||selectedIds.has(idOf(x))||selectedIds.has(first(x,["activity_id"]))).slice(0,8);
 return <section className="ulb-command" aria-label="Institutional command center"><div className="ulb-head"><div><p className="eyebrow">INSTITUTIONAL COMMAND CENTRE</p><h2>{membership?.organization_name}</h2><p>City / local-body operating view · authoritative records only</p></div><button className="secondary" onClick={()=>void refresh()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div>
  <div className="ulb-metrics"><article><span>RESOURCE FLOWS</span><strong>{Number(counts.activities??flows.length)}</strong><small>Recorded operational activity</small></article><article><span>MEASUREMENTS</span><strong>{Number(counts.measurements??measurements.length)}</strong><small>Quantity records</small></article><article><span>EVIDENCE</span><strong>{Number(counts.evidence??evidence.length)}</strong><small>Evidence records</small></article><article><span>VERIFIED</span><strong>{verified}</strong><small>Approved verification</small></article><article><span>OPEN OBLIGATIONS</span><strong>{open}</strong><small>Compliance items</small></article></div>
  <div className="ulb-drill"><div className="ulb-drill-head"><div><p className="eyebrow">OPERATIONAL DRILL-DOWN</p><h3>Follow the authoritative chain</h3><p>Use only geography and facility attributes already present in returned records. Empty dimensions remain unavailable rather than being inferred.</p></div><div className="ulb-filters"><label>Geography<select value={geo} onChange={e=>{setGeo(e.target.value);setFacility("ALL")}}><option value="ALL">All available</option>{geographies.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Facility<select value={facility} onChange={e=>setFacility(e.target.value)}><option value="ALL">All available</option>{facilities.map(x=><option key={x} value={x}>{x}</option>)}</select></label></div></div>
   <div className="ulb-chain"><article><span>1 · FLOW</span><strong>{selectedFlows.length}</strong><small>matching operational records</small></article><article><span>2 · MEASUREMENT</span><strong>{selectedMeasurements.length}</strong><small>linked records when IDs permit</small></article><article><span>3 · EVIDENCE</span><strong>{selectedEvidence.length}</strong><small>linked records when IDs permit</small></article><article><span>4 · VERIFICATION</span><strong>{selectedVerifications.length}</strong><small>linked records when IDs permit</small></article></div>
   <div className="ulb-table-wrap"><table><thead><tr><th>Flow / Activity</th><th>Geography</th><th>Facility</th><th>Flow status</th><th>Measurement</th><th>Evidence</th><th>Verification</th></tr></thead><tbody>{selectedFlows.slice(0,12).map((f,i)=>{const id=idOf(f);const a=activities.find(x=>id&&idOf(x)===id||id&&first(x,["activity_id"])===id);const m=measurements.find(x=>id&&first(x,["activity_id","measurement_activity_id"])===id);const ev=evidence.find(x=>id&&first(x,["activity_id"])===id);const vr=verifications.find(x=>id&&first(x,["activity_id"])===id);const linked=m??a??{};return <tr key={id||i}><td><strong>{id||"Unavailable"}</strong></td><td>{geoOf(f)||"UNAVAILABLE"}</td><td>{facilityOf(f)||"UNAVAILABLE"}</td><td>{statusOf(f)}</td><td>{m||a?statusOf(linked):"UNAVAILABLE"}</td><td>{ev?statusOf(ev):"UNAVAILABLE"}</td><td>{vr?statusOf(vr):"UNAVAILABLE"}</td></tr>})}</tbody></table>{!selectedFlows.length&&<p className="ulb-empty">No resource-flow records match the selected dimensions, or the authoritative source does not expose those dimensions.</p>}</div>
  </div>
  <div className="ulb-grid"><article><p className="eyebrow">OPERATIONS</p><h3>What is moving?</h3><p>Resource-flow records available in this organization and geography scope.</p><div className="ulb-stat">{flows.length}<span>records loaded</span></div></article><article><p className="eyebrow">MRV READINESS</p><h3>What is proven?</h3><div className="ulb-checks"><span>Activities <b>{activities.length}</b></span><span>Measurements <b>{measurements.length}</b></span><span>Evidence <b>{evidence.length}</b></span><span>Approved verification <b>{verified}</b></span></div></article><article><p className="eyebrow">COMPLIANCE</p><h3>What needs attention?</h3><div className="ulb-stat">{open}<span>open obligations</span></div><p className="ulb-note">No obligation is treated as satisfied unless an authoritative record says so.</p></article></div>
  <div className="ulb-boundary"><div><p className="eyebrow">GOVERNANCE BOUNDARY</p><strong>Operational visibility ≠ regulatory issuance.</strong><p>RupayKg can show activity, evidence, verification and compliance state. Credential issuance, external registry consensus, government acceptance and settlement remain separate authoritative stages.</p></div><div className="ulb-source">Source: PostgreSQL<br/>Synthetic data: {ops?.syntheticData===true?"true":"false"}</div></div>{error&&<p className="error">{error}</p>}</section>;
}
function mount(){let root=document.getElementById("ulb-command-center");if(!root){root=document.createElement("div");root.id="ulb-command-center";const anchor=document.getElementById("carbon-command-center")??document.getElementById("root");anchor?.parentElement?.insertBefore(root,anchor.nextSibling);if(!root.isConnected)return}import("react-dom/client").then(({createRoot})=>createRoot(root!).render(<ULBCommandCenter/>));}mount();
