import type { FastifyInstance } from "fastify";
import type { Pool, PoolClient } from "pg";
import { authenticate, canActForOrganization, canPerformHighRiskActionInDatabase, type AuthContext } from "./auth.js";

type Reply={code:(status:number)=>{send:(body:unknown)=>unknown}};
type Request={body:unknown;params:Record<string,string>;log:{error:(error:unknown)=>void}};
const bodyOf=(r:Request):Record<string,unknown>=>r.body&&typeof r.body==="object"?r.body as Record<string,unknown>:{};
const str=(b:Record<string,unknown>,k:string):string|null=>typeof b[k]==="string"&&b[k].trim()?b[k].trim():null;
const positive=(b:Record<string,unknown>,k:string):number|null=>{const n=Number(b[k]);return Number.isFinite(n)&&n>0?n:null};
async function authFor(r:Request,reply:Reply,pool:Pool|null):Promise<AuthContext|null>{
  if(!pool){reply.code(503).send({error:"Database unavailable",code:"DATABASE_UNAVAILABLE"});return null}
  try{const auth=await authenticate(r as never,pool);if(!auth){reply.code(401).send({error:"Authenticated session required",code:"AUTH_REQUIRED"});return null}return auth}
  catch(error){r.log.error(error);reply.code(503).send({error:"Authentication service unavailable",code:"AUTH_UNAVAILABLE"});return null}
}
async function tx<T>(pool:Pool,fn:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await pool.connect();try{await client.query("begin");const result=await fn(client);await client.query("commit");return result}catch(error){await client.query("rollback");throw error}finally{client.release()}}

export async function registerRegistryRoutes(app:FastifyInstance,pool:Pool|null):Promise<void>{
  app.post("/api/v1/credentials",async(request,reply)=>{
    const auth=await authFor(request as never,reply,pool);if(!auth||!pool)return;const b=bodyOf(request as never);
    const activityId=str(b,"activityId"),trustRootId=str(b,"trustRootId"),verificationId=str(b,"verificationId"),issuerOrganizationId=str(b,"issuerOrganizationId"),quantity=positive(b,"quantity"),unit=str(b,"unit");
    if(!activityId||!trustRootId||!verificationId||!issuerOrganizationId||quantity===null||!unit)return reply.code(400).send({error:"activityId, trustRootId, verificationId, issuerOrganizationId, positive quantity and unit are required"});
    if(!canActForOrganization(auth,issuerOrganizationId))return reply.code(403).send({error:"Issuer organization access denied",code:"ORG_FORBIDDEN"});
    if(!await canPerformHighRiskActionInDatabase(pool,auth,issuerOrganizationId,"ISSUE_CREDENTIAL"))return reply.code(403).send({error:"Explicit ISSUE_CREDENTIAL permission is required",code:"HIGH_RISK_PERMISSION_REQUIRED"});
    try{return reply.code(201).send({source:"postgresql",syntheticData:false,credential:await tx(pool,async c=>{
      const v=await c.query<{evidence_id:string;decision:string}>("select evidence_id,decision from verifications where id=$1 for update",[verificationId]);
      if(!v.rows[0]||v.rows[0].decision!=="APPROVED")throw Object.assign(new Error("Approved verification required"),{code:"VERIFICATION_REQUIRED"});
      const e=await c.query<{activity_id:string|null;status:string}>("select activity_id,status from evidence where id=$1 for update",[v.rows[0].evidence_id]);
      if(!e.rows[0]||e.rows[0].status!=="VERIFIED"||e.rows[0].activity_id!==activityId)throw Object.assign(new Error("Verification is not bound to verified activity evidence"),{code:"EVIDENCE_MISMATCH"});
      const a=await c.query<{organization_id:string;status:string}>("select organization_id,status from activities where id=$1 for update",[activityId]);
      if(!a.rows[0]||a.rows[0].organization_id!==issuerOrganizationId||a.rows[0].status!=="COMPLETED")throw Object.assign(new Error("Completed activity owned by issuer is required"),{code:"ACTIVITY_NOT_ELIGIBLE"});
      const existing=await c.query("select id from credentials where activity_id=$1 and verification_id=$2",[activityId,verificationId]);if(existing.rows[0])throw Object.assign(new Error("Credential already exists for verification"),{code:"CREDENTIAL_EXISTS"});
      const inserted=await c.query("insert into credentials(activity_id,issuer_organization_id,trust_root_id,status,verification_id,quantity,unit,issued_at) values($1,$2,$3,'ISSUED',$4,$5,$6,now()) returning *",[activityId,issuerOrganizationId,trustRootId,verificationId,quantity,unit]);
      await c.query("insert into registry_events(credential_id,event_type,from_owner_id,to_owner_id,verification_id,recorded_by_identity_id,event_hash) values($1,'ISSUED',null,$2,$3,$4,$5)",[inserted.rows[0].id,issuerOrganizationId,verificationId,auth.identityId,`issue:${inserted.rows[0].id}:${verificationId}`]);return inserted.rows[0]
    })})}catch(error){request.log.error(error);const code=(error as {code?:string}).code;if(code==="HIGH_RISK_PERMISSION_REQUIRED")return reply.code(403).send({error:(error as Error).message,code});if(["VERIFICATION_REQUIRED","EVIDENCE_MISMATCH","ACTIVITY_NOT_ELIGIBLE","CREDENTIAL_EXISTS"].includes(code??""))return reply.code(409).send({error:(error as Error).message,code});return reply.code(503).send({error:"Credential issuance unavailable",syntheticData:false})}
  });

  app.post("/api/v1/credentials/:credentialId/activate",async(request,reply)=>{
    const auth=await authFor(request as never,reply,pool);if(!auth||!pool)return;const id=(request.params as {credentialId:string}).credentialId;
    try{return {source:"postgresql",syntheticData:false,credential:await tx(pool,async c=>{const r=await c.query<{status:string;issuer_organization_id:string}>("select status,issuer_organization_id from credentials where id=$1 for update",[id]);if(!r.rows[0])throw Object.assign(new Error("Credential not found"),{code:"NOT_FOUND"});if(!canActForOrganization(auth,r.rows[0].issuer_organization_id))throw Object.assign(new Error("Organization access denied"),{code:"ORG_FORBIDDEN"});if(!await canPerformHighRiskActionInDatabase(c,auth,r.rows[0].issuer_organization_id,"ISSUE_CREDENTIAL"))throw Object.assign(new Error("Explicit ISSUE_CREDENTIAL permission is required"),{code:"HIGH_RISK_PERMISSION_REQUIRED"});if(r.rows[0].status!=="ISSUED")throw Object.assign(new Error("Credential must be ISSUED before activation"),{code:"INVALID_TRANSITION"});const u=await c.query("update credentials set status='ACTIVE' where id=$1 returning *",[id]);await c.query("insert into registry_events(credential_id,event_type,to_owner_id,recorded_by_identity_id,event_hash) values($1,'ACTIVATED',$2,$3,$4)",[id,r.rows[0].issuer_organization_id,auth.identityId,`activate:${id}`]);return u.rows[0]})}}
    catch(error){const code=(error as {code?:string}).code;if(code==="NOT_FOUND")return reply.code(404).send({error:"Credential not found"});if(code==="ORG_FORBIDDEN"||code==="HIGH_RISK_PERMISSION_REQUIRED")return reply.code(403).send({error:(error as Error).message,code});if(code==="INVALID_TRANSITION")return reply.code(409).send({error:(error as Error).message,code});request.log.error(error);return reply.code(503).send({error:"Credential activation unavailable",syntheticData:false})}
  });

  app.post("/api/v1/credentials/:credentialId/transfer",async(request,reply)=>{
    const auth=await authFor(request as never,reply,pool);if(!auth||!pool)return;const id=(request.params as {credentialId:string}).credentialId,toOwnerId=str(bodyOf(request as never),"toOwnerId");if(!toOwnerId)return reply.code(400).send({error:"toOwnerId is required"});
    try{return {source:"postgresql",syntheticData:false,registryEvent:await tx(pool,async c=>{const r=await c.query<{status:string}>("select status from credentials where id=$1 for update",[id]);if(!r.rows[0])throw Object.assign(new Error("Credential not found"),{code:"NOT_FOUND"});const o=await c.query<{to_owner_id:string|null}>("select to_owner_id from registry_events where credential_id=$1 and event_type in('ISSUED','TRANSFERRED') order by created_at desc limit 1",[id]);const owner=o.rows[0]?.to_owner_id;if(!owner||!canActForOrganization(auth,owner))throw Object.assign(new Error("Current owner access denied"),{code:"ORG_FORBIDDEN"});if(!await canPerformHighRiskActionInDatabase(c,auth,owner,"TRANSFER_CREDENTIAL"))throw Object.assign(new Error("Explicit TRANSFER_CREDENTIAL permission is required"),{code:"HIGH_RISK_PERMISSION_REQUIRED"});if(r.rows[0].status!=="ACTIVE")throw Object.assign(new Error("Only ACTIVE credentials can be transferred"),{code:"INVALID_TRANSITION"});const target=await c.query("select id from organizations where id=$1",[toOwnerId]);if(!target.rows[0])throw Object.assign(new Error("Destination organization not found"),{code:"DESTINATION_NOT_FOUND"});await c.query("update credentials set status='TRANSFERRED' where id=$1",[id]);const e=await c.query("insert into registry_events(credential_id,event_type,from_owner_id,to_owner_id,recorded_by_identity_id,event_hash) values($1,'TRANSFERRED',$2,$3,$4,$5) returning *",[id,owner,toOwnerId,auth.identityId,`transfer:${id}:${owner}:${toOwnerId}:${Date.now()}`]);return e.rows[0]})}}
    catch(error){const code=(error as {code?:string}).code;if(code==="NOT_FOUND")return reply.code(404).send({error:"Credential not found"});if(code==="ORG_FORBIDDEN"||code==="HIGH_RISK_PERMISSION_REQUIRED")return reply.code(403).send({error:(error as Error).message,code});if(code==="INVALID_TRANSITION"||code==="DESTINATION_NOT_FOUND")return reply.code(409).send({error:(error as Error).message,code});request.log.error(error);return reply.code(503).send({error:"Credential transfer unavailable",syntheticData:false})}
  });

  app.post("/api/v1/credentials/:credentialId/retire",async(request,reply)=>{
    const auth=await authFor(request as never,reply,pool);if(!auth||!pool)return;const id=(request.params as {credentialId:string}).credentialId;
    try{return {source:"postgresql",syntheticData:false,registryEvent:await tx(pool,async c=>{const r=await c.query<{status:string}>("select status from credentials where id=$1 for update",[id]);if(!r.rows[0])throw Object.assign(new Error("Credential not found"),{code:"NOT_FOUND"});const o=await c.query<{owner_id:string|null}>("select coalesce(to_owner_id,from_owner_id) owner_id from registry_events where credential_id=$1 order by created_at desc limit 1",[id]);if(!o.rows[0]?.owner_id||!canActForOrganization(auth,o.rows[0].owner_id))throw Object.assign(new Error("Current owner access denied"),{code:"ORG_FORBIDDEN"});if(!await canPerformHighRiskActionInDatabase(c,auth,o.rows[0].owner_id,"RETIRE_CREDENTIAL"))throw Object.assign(new Error("Explicit RETIRE_CREDENTIAL permission is required"),{code:"HIGH_RISK_PERMISSION_REQUIRED"});if(!["ACTIVE","TRANSFERRED"].includes(r.rows[0].status))throw Object.assign(new Error("Credential is not retireable"),{code:"INVALID_TRANSITION"});const openSettlement=await c.query("select id from settlements where credential_id=$1 and status not in('SETTLED','CANCELLED') limit 1",[id]);if(openSettlement.rows[0])throw Object.assign(new Error("Credential cannot be retired while a settlement is open"),{code:"OPEN_SETTLEMENT"});await c.query("update credentials set status='RETIRED' where id=$1",[id]);const e=await c.query("insert into registry_events(credential_id,event_type,from_owner_id,recorded_by_identity_id,event_hash) values($1,'RETIRED',$2,$3,$4) returning *",[id,o.rows[0].owner_id,auth.identityId,`retire:${id}:${Date.now()}`]);return e.rows[0]})}}
    catch(error){const code=(error as {code?:string}).code;if(code==="NOT_FOUND")return reply.code(404).send({error:"Credential not found"});if(code==="ORG_FORBIDDEN"||code==="HIGH_RISK_PERMISSION_REQUIRED")return reply.code(403).send({error:(error as Error).message,code});if(code==="INVALID_TRANSITION"||code==="OPEN_SETTLEMENT")return reply.code(409).send({error:(error as Error).message,code});request.log.error(error);return reply.code(503).send({error:"Credential retirement unavailable",syntheticData:false})}
  });

  app.post("/api/v1/settlements",async(request,reply)=>{
    const auth=await authFor(request as never,reply,pool);if(!auth||!pool)return;const b=bodyOf(request as never);const credentialId=str(b,"credentialId"),payerId=str(b,"payerId"),payeeId=str(b,"payeeId"),currency=str(b,"currency"),amount=positive(b,"amount");if(!credentialId||!payerId||!payeeId||amount===null||!currency||currency.length!==3)return reply.code(400).send({error:"credentialId, payerId, payeeId, positive amount and 3-letter currency are required"});if(!canActForOrganization(auth,payerId)&&!canActForOrganization(auth,payeeId))return reply.code(403).send({error:"Settlement party access denied",code:"ORG_FORBIDDEN"});
    try{return reply.code(201).send({source:"postgresql",syntheticData:false,settlement:await tx(pool,async c=>{const cr=await c.query<{status:string}>("select status from credentials where id=$1 for update",[credentialId]);if(!cr.rows[0])throw Object.assign(new Error("Credential not found"),{code:"NOT_FOUND"});if(cr.rows[0].status==="RETIRED")throw Object.assign(new Error("Retired credentials cannot create settlements"),{code:"CREDENTIAL_RETIRED"});if(!["ACTIVE","TRANSFERRED"].includes(cr.rows[0].status))throw Object.assign(new Error("Credential must have an authoritative registry state before settlement"),{code:"REGISTRY_REQUIRED"});const ev=await c.query("select id from registry_events where credential_id=$1 and event_type in('ISSUED','TRANSFERRED','RETIRED') order by created_at desc limit 1",[credentialId]);if(!ev.rows[0])throw Object.assign(new Error("Authoritative registry event required"),{code:"REGISTRY_REQUIRED"});const s=await c.query("insert into settlements(credential_id,payer_id,payee_id,amount,currency,status,external_reference) values($1,$2,$3,$4,$5,'CREATED',$6) returning *",[credentialId,payerId,payeeId,amount,currency,str(b,"externalReference")]);return s.rows[0]})})}catch(error){const code=(error as {code?:string}).code;if(code==="NOT_FOUND")return reply.code(404).send({error:"Credential not found"});if(code==="REGISTRY_REQUIRED"||code==="CREDENTIAL_RETIRED")return reply.code(409).send({error:(error as Error).message,code});request.log.error(error);return reply.code(503).send({error:"Settlement creation unavailable",syntheticData:false})}
  });

  app.post("/api/v1/settlements/:settlementId/authorize",async(request,reply)=>{
    const auth=await authFor(request as never,reply,pool);if(!auth||!pool)return;const id=(request.params as {settlementId:string}).settlementId,ref=str(bodyOf(request as never),"authorizationReference");if(!ref)return reply.code(400).send({error:"authorizationReference is required"});
    try{return {source:"postgresql",syntheticData:false,settlement:await tx(pool,async c=>{const r=await c.query<{status:string;payer_id:string;payee_id:string}>("select status,payer_id,payee_id from settlements where id=$1 for update",[id]);if(!r.rows[0])throw Object.assign(new Error("Settlement not found"),{code:"NOT_FOUND"});const organizationId=canActForOrganization(auth,r.rows[0].payer_id)?r.rows[0].payer_id:canActForOrganization(auth,r.rows[0].payee_id)?r.rows[0].payee_id:null;if(!organizationId)throw Object.assign(new Error("Settlement party access denied"),{code:"ORG_FORBIDDEN"});if(!await canPerformHighRiskActionInDatabase(c,auth,organizationId,"AUTHORIZE_SETTLEMENT"))throw Object.assign(new Error("Explicit AUTHORIZE_SETTLEMENT permission is required"),{code:"HIGH_RISK_PERMISSION_REQUIRED"});if(r.rows[0].status!=="CREATED")throw Object.assign(new Error("Settlement must be CREATED before authorization"),{code:"INVALID_TRANSITION"});const u=await c.query("update settlements set status='AUTHORIZED',authorization_reference=$2,verified_at=now() where id=$1 returning *",[id,ref]);await c.query("insert into settlement_events(settlement_id,event_type,actor_identity_id,external_reference,event_hash) values($1,'AUTHORIZED',$2,$3,$4)",[id,auth.identityId,ref,`authorize:${id}:${ref}`]);return u.rows[0]})}}
    catch(error){const code=(error as {code?:string}).code;if(code==="NOT_FOUND")return reply.code(404).send({error:"Settlement not found"});if(code==="ORG_FORBIDDEN"||code==="HIGH_RISK_PERMISSION_REQUIRED")return reply.code(403).send({error:(error as Error).message,code});if(code==="INVALID_TRANSITION")return reply.code(409).send({error:(error as Error).message,code});request.log.error(error);return reply.code(503).send({error:"Settlement authorization unavailable",syntheticData:false})}
  });

  app.post("/api/v1/settlements/:settlementId/settle",async(request,reply)=>{
    const auth=await authFor(request as never,reply,pool);if(!auth||!pool)return;const id=(request.params as {settlementId:string}).settlementId,ref=str(bodyOf(request as never),"externalReference");if(!ref)return reply.code(400).send({error:"externalReference is required"});
    try{return {source:"postgresql",syntheticData:false,settlement:await tx(pool,async c=>{const r=await c.query<{status:string;payer_id:string;payee_id:string}>("select status,payer_id,payee_id from settlements where id=$1 for update",[id]);if(!r.rows[0])throw Object.assign(new Error("Settlement not found"),{code:"NOT_FOUND"});const organizationId=canActForOrganization(auth,r.rows[0].payer_id)?r.rows[0].payer_id:canActForOrganization(auth,r.rows[0].payee_id)?r.rows[0].payee_id:null;if(!organizationId)throw Object.assign(new Error("Settlement party access denied"),{code:"ORG_FORBIDDEN"});if(!await canPerformHighRiskActionInDatabase(c,auth,organizationId,"SETTLE_FUNDS"))throw Object.assign(new Error("Explicit SETTLE_FUNDS permission is required"),{code:"HIGH_RISK_PERMISSION_REQUIRED"});if(r.rows[0].status!=="AUTHORIZED")throw Object.assign(new Error("Settlement must be AUTHORIZED before execution"),{code:"INVALID_TRANSITION"});await c.query("update settlements set status='EXECUTING',external_reference=$2 where id=$1",[id,ref]);await c.query("insert into settlement_events(settlement_id,event_type,actor_identity_id,external_reference,event_hash) values($1,'EXECUTING',$2,$3,$4)",[id,auth.identityId,ref,`execute:${id}:${ref}`]);const u=await c.query("update settlements set status='RECONCILING' where id=$1 returning *",[id]);return u.rows[0]})}}
    catch(error){const code=(error as {code?:string}).code;if(code==="NOT_FOUND")return reply.code(404).send({error:"Settlement not found"});if(code==="ORG_FORBIDDEN"||code==="HIGH_RISK_PERMISSION_REQUIRED")return reply.code(403).send({error:(error as Error).message,code});if(code==="INVALID_TRANSITION")return reply.code(409).send({error:(error as Error).message,code});request.log.error(error);return reply.code(503).send({error:"Settlement execution unavailable",syntheticData:false})}
  });

  app.post("/api/v1/settlements/:settlementId/confirm",async(request,reply)=>{
    const auth=await authFor(request as never,reply,pool);if(!auth||!pool)return;const id=(request.params as {settlementId:string}).settlementId,b=bodyOf(request as never);const confirmationReference=str(b,"confirmationReference"),reconciliationReference=str(b,"reconciliationReference");
    if(!confirmationReference||!reconciliationReference)return reply.code(400).send({error:"confirmationReference and reconciliationReference are required from the external settlement authority/reconciliation process"});
    try{return {source:"postgresql",syntheticData:false,settlement:await tx(pool,async c=>{const r=await c.query<{status:string;payer_id:string;payee_id:string;external_reference:string|null}>("select status,payer_id,payee_id,external_reference from settlements where id=$1 for update",[id]);if(!r.rows[0])throw Object.assign(new Error("Settlement not found"),{code:"NOT_FOUND"});const organizationId=canActForOrganization(auth,r.rows[0].payer_id)?r.rows[0].payer_id:canActForOrganization(auth,r.rows[0].payee_id)?r.rows[0].payee_id:null;if(!organizationId)throw Object.assign(new Error("Settlement party access denied"),{code:"ORG_FORBIDDEN"});if(!await canPerformHighRiskActionInDatabase(c,auth,organizationId,"SETTLE_FUNDS"))throw Object.assign(new Error("Explicit SETTLE_FUNDS permission is required"),{code:"HIGH_RISK_PERMISSION_REQUIRED"});if(r.rows[0].status!=="RECONCILING")throw Object.assign(new Error("Settlement must be RECONCILING before confirmation"),{code:"INVALID_TRANSITION"});if(!r.rows[0].external_reference)throw Object.assign(new Error("Executed settlement requires external settlement reference"),{code:"EXTERNAL_REFERENCE_REQUIRED"});const u=await c.query("update settlements set status='SETTLED',settled_at=now(),external_confirmed_at=now(),reconciliation_reference=$2 where id=$1 returning *",[id,reconciliationReference]);await c.query("insert into settlement_events(settlement_id,event_type,actor_identity_id,external_reference,event_hash) values($1,'SETTLED',$2,$3,$4)",[id,auth.identityId,confirmationReference,`settled:${id}:${confirmationReference}:${reconciliationReference}`]);return u.rows[0]})}}
    catch(error){const code=(error as {code?:string}).code;if(code==="NOT_FOUND")return reply.code(404).send({error:"Settlement not found"});if(code==="ORG_FORBIDDEN"||code==="HIGH_RISK_PERMISSION_REQUIRED")return reply.code(403).send({error:(error as Error).message,code});if(code==="INVALID_TRANSITION"||code==="EXTERNAL_REFERENCE_REQUIRED")return reply.code(409).send({error:(error as Error).message,code});request.log.error(error);return reply.code(503).send({error:"Settlement confirmation unavailable",syntheticData:false})}
  });
}